### ISSUE TITLE
ETW is not supported on all platforms

### ISSUE THREAD

**Issue by inelisoni** [microsoft/Microsoft.IO.RecyclableMemoryStream#101]
For example, Unity on some platforms (e.g. Android) replaces the body of methods marked with EventAttribute with `throw new NotSupportedException("linked away")`, which results in runtime exceptions.

It would be nice to have automatic detection of ETW support (at worst ability to disable ETW from application code, e.g. set `Events.Writer` to null).

**Comment by benmwatson** [comment]
I was not aware of this behavior, to introduce exceptions. That's kind of a bummer for code that compiles against netstandard. Is there a way to change the compiler to replace it with no-ops instead?

**Comment by Starsmiao** [comment]
> For example, Unity on some platforms (e.g. Android) replaces the body of methods marked with EventAttribute with `throw new NotSupportedException("linked away")`, which results in runtime exceptions.
> 
> It would be nice to have automatic detection of ETW support (at worst ability to disable ETW from application code, e.g. set `Events.Writer` to null).

I got the same 'NotSupportedException' problem using Unity2019.4 or newer version on android. Have you got any progress？

**Comment by benmwatson** [comment]
I keep going back and forth on this. It's not TOO hard to add a boolean to allow people to disable event logging, but it does make the code quite a bit uglier with an extra and, IMO, unnecessary abstraction just to work around a weird platform quirk.

EventSource is a standard part of the the .NET Core API and is supported by netstandard back to version 1.1. I'm not at all familiar with Unity, but I did find a page mentioning something about a [netstandard API compatibility mode](https://forum.unity.com/threads/notsupportedexception-with-log-detail.543644/#post-3588014) for compilation. Have you tried that? Have you looked [here](https://docs.unity3d.com/Manual/dotnetProfileSupport.html)?

**Comment by Starsmiao** [comment]
> I keep going back and forth on this. It's not TOO hard to add a boolean to allow people to disable event logging, but it does make the code quite a bit uglier with an extra and, IMO, unnecessary abstraction just to work around a weird platform quirk.
> 
> EventSource is a standard part of the the .NET Core API and is supported by netstandard back to version 1.1. I'm not at all familiar with Unity, but I did find a page mentioning something about a [netstandard API compatibility mode](https://forum.unity.com/threads/notsupportedexception-with-log-detail.543644/#post-3588014) for compilation. Have you tried that? Have you looked [here](https://docs.unity3d.com/Manual/dotnetProfileSupport.html)?

Thanks for the reply. I am so sorry for the huge delay and this stupid question. I found out the reason couple days ago and was busy and forgot to reply. I have tried to switch to netstandard but it was not help and finally I found out it was the Unity IL2CPP stripped the 'System.Diagnostics.Tracing' from system dll and caused the 'NotSupportedException' problem.

**Comment by inelisoni** [comment]
> I keep going back and forth on this. It's not TOO hard to add a boolean to allow people to disable event logging, but it does make the code quite a bit uglier with an extra and, IMO, unnecessary abstraction just to work around a weird platform quirk.

I agree with you. The problem is on Unity side.
