### ISSUE TITLE
How bad would be if I had multiple instances of the manager?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/Microsoft.IO.RecyclableMemoryStream#104]
I have 2 usage cases for memory streams in my app. For case 1, the `BlockSize = 8192` is ideal and for case 2, `1024` is the magic number... how bad would be if I had 2 instances of the manager?

**Comment by benmwatson** [comment]
There is nothing inherently wrong with this. If you have to divergent use cases, feel free to do it.
