### ISSUE TITLE
Allow Partially Trusted Callers

### ISSUE THREAD

**Issue by JanKallman** [microsoft/Microsoft.IO.RecyclableMemoryStream#108]
I have a pull request to implement this library into EPPlus... https://github.com/EPPlusSoftware/EPPlus/pull/207, which seems like a good idea.
But we run into a problem as this library does not have the AllowPartiallyTrustedCallers attribute set, so EPPlus fails on .NET 4 or .NET 4.5. 
Is this intentionally left out for some reason or is it something that can be added?

**Comment by benmwatson** [comment]
Let me look into this in more detail. I think this could be easily done.

**Comment by JanKallman** [comment]
Thanks!

**Comment by LIFEfreedom** [comment]
I added the **AllowPartiallyTrustedCallers** attribute and all tests succeeded. `Could not access method` error not occurred

**Comment by benmwatson** [comment]
Would you like to submit a PR for this change?

**Comment by LIFEfreedom** [comment]
yes, i created PR for this change

**Comment by LIFEfreedom** [comment]
@benmwatson When can this change be observed in Nuget?

**Comment by benmwatson** [comment]
I will be publishing a new version today.

**Comment by LIFEfreedom** [comment]
Thanks!
