### ISSUE TITLE
Why is disposed state using Interlocked?

### ISSUE THREAD

**Issue by paulomorgado** [microsoft/Microsoft.IO.RecyclableMemoryStream#111]
This is being used in all invocations of the stream.

is there any concurrent work going on that I'm not aware of?

**Comment by benmwatson** [comment]
In general, concurrent reading/writing to a stream is not supported, but there were some use cases where there was concurrent checking of whether a stream was disposed, and also to guard against double-dispose in different threads.

**Comment by paulomorgado** [comment]
Wouldn't scoping it only to `Dispose` be a better option, then?

**Comment by benmwatson** [comment]
Looking through this, I agree. The only place it *might* be needed is in Dispose() itself. That's questionable, but I'm inclined to leave that for now. If you submit a PR, I can take a look, or I'll try to do this soon.

**Comment by paulomorgado** [comment]
Are the mentioned use cases covered by tests?

**Comment by benmwatson** [comment]
There is a simple test case for concurrent double-dispose, but that's it. I think it's ok to remove the other interlocked usage.

**Comment by Therzok** [comment]
Not using Interlocked on reading the Disposed value could end up with reading the wrong value, since it's not doing an atomic read in 32bit contexts.

**Comment by paulomorgado** [comment]
I understand that.

My initial question was if this is a use case we should account for. What is the use case for using the stream concurrently?

**Comment by benmwatson** [comment]
For v2.0, I'm going to remove the Interlocked calls. I don't think there's any valid use cases for concurrent usage of the stream. I'll make sure the documentation makes this clear.
