### ISSUE TITLE
CopyToAsync does not take current position into account

### ISSUE THREAD

**Issue by DavidZidar** [microsoft/Microsoft.IO.RecyclableMemoryStream#115]
The regular `MemoryStream` copies data from the current position and so does RecyclableMemoryStream version 1.3.5 but version 1.3.6 copies from the beginning regardless of position which is unexpected.

This breaks my use case because I often read stream headers and then copy the remainder.

The problem can easily be reproduced like this:
```
var manager = new RecyclableMemoryStreamManager();
using var input = manager.GetStream();
input.WriteByte(1);
input.WriteByte(2);
input.Seek(1, SeekOrigin.Begin);
using var output = new MemoryStream();
await input.CopyToAsync(output);

output.Length // Should now be 1, but is 2 with version 1.3.6
```

**Comment by benmwatson** [comment]
Thanks for reporting it. We've been changing how CopyToAsync is implemented. I'll look into this soon.

**Comment by benmwatson** [comment]
@DavidZidar and @paulomorgado Could you please take a look at the related PR to resolve this?
