### ISSUE TITLE
The following piece of code hangs the write call

### ISSUE THREAD

**Issue by ghost** [Microsoft/Microsoft.IO.RecyclableMemoryStream#12]
RecyclableMemoryStreamManager manager = new RecyclableMemoryStreamManager();
manager.GenerateCallStacks = true;
RecyclableMemoryStream stream = new RecyclableMemoryStream(manager, "Tag1");
StreamWriter writer = new StreamWriter(stream);
for(long i=0;i<1024 *1024 * 1024;i++)
{
	writer.Write('c');
}
for(long i=0;i<1024 *1024 * 1024;i++)
{
	writer.Write('c');
}
writer.Flush();

The second loop hangs at I value 1073611776

**Comment by benmwatson** [comment]
Thank you. Will investigate.

**Comment by stakx** [comment]
`StreamWriter` uses UTF-8 as the default encoding, which means that your two loops attempt to write 2 GiB of data into the buffer. AFAIK, 32 bit .NET processes have a memory limit of 2 GB, so I would assume that this program simply uses up all available memory.

**Comment by doubleyewdee** [comment]
Have a PR to fix this. It's actually a problem with the Capacity property of the streams not correctly handling integer overflow causing a degenerative case. (See issue #26 which I will close this in favor of).

My apologies for the delayed response here.
