### ISSUE TITLE
Adding the stream guid and tag to the Stream Finalized C# event

### ISSUE THREAD

**Issue by BazookaMusic** [microsoft/Microsoft.IO.RecyclableMemoryStream#125]
Currently the C# events for stream finalization, disposal and so on, do not receive the string id and tag of the streams finalized as arguments. They also do not receive the size. This prevents someone from writing code dependent on the stream which is being finalized.

Some potential uses that this would enable are:
1) Hooking up a custom telemetry system to monitor leaks by using the tags or the guids and emitting from C#
2) Using the string tag as a category and implementing per application area statistics
3) Unique events per stream type

A suggestion would be to add these arguments as they're available at the point that these events are emitted and they would enable a lot of uses for the events.

**Comment by benmwatson** [comment]
My main concern is performance. Adding this information means passing arguments to the events, which until this have been simple affairs. I'll consider each event individually to decide what kind of data should be passed. I don't want to completely duplicate the ETW functionality, but providing a way to customize response to various events is nice too.

**Comment by BazookaMusic** [comment]
I created this simple Linqpad program to use with BenchmarkDotNet to give some data on this. It's pretty trivial, hacked together from online examples and compares 3 scenarios:
1) Invoking an event without arguments
2) Invoking an event with a guid and a string argument
3) Writing 10 bytes to a regular memory stream (light workload simulation) 

The results for net core 3.1 were the following:
                     Mean.        Error
1) NoArgs: 0.8350ns    0.0327ns
2) Args:       2.1824ns.   0.0181ns
3) Stream:  42.1784ns 0.1196ns

The results for net core 5.0 were the following:
                     Mean.        Error
1) NoArgs: 1.116ns    0.0168ns
2) Args:       1.746ns.   0.0158ns
3) Stream:  40.839ns   0.1324ns

Adding the arguments can more than double the runtime, but on the other hand, we're still talking about a few nanoseconds per invocation. Seeing as writing just 10 bytes to a stream is 40 times slower, I do not believe that adding the arguments will be an important performance hit. This of course depends on the requirements of the applications consuming the library. My benchmark is also not extremely representative of the actual usage of the library. 

```c#
#LINQPad optimize+
void Main()
{
	var summary = BenchmarkRunner.Run<NoArgsVsArgs>();
}

public class NoArgsVsArgs
{
	Publisher args, noargs;

	public NoArgsVsArgs()
	{
		this.args = new Publisher();
		this.noargs = new Publisher();

		this.args.EventWithArgs += (Guid e, string s) =>
		{
		};

		this.args.EventNoArgs += () =>
		{
		};
	}

	[Benchmark]
	public void NoArgs() => this.noargs.RaiseEventWithArgs();

	[Benchmark]
	public void Args() => this.args.RaiseEventNoArgs();

	[Benchmark]
	public void MemoryStreamWrite() 
	{
		this.args.stream.Position = 0;
		for (int i = 0; i < 10; i++)
		{
			this.args.stream.WriteByte(255);
		}
	}

}

public class EventWithArgsArgs
{
    public EventWithArgsArgs(string text) { Text = text; }
    public string Text { get; } // readonly
}

public class Publisher
{
	string str = "aaaaa";
	Guid gu = Guid.Empty;
	
	public MemoryStream stream = new MemoryStream(100);
	
	// Declare the delegate (if using non-generic pattern).
    public delegate void EventWithArgsHandler(Guid e, string s);

    // Declare the event.
    public event EventWithArgsHandler EventWithArgs;
	
	// Declare the delegate (if using non-generic pattern).
    public delegate void EventWithArgsHandler2();

    // Declare the event.
    public event EventWithArgsHandler2 EventNoArgs;

    // Wrap the event in a protected virtual method
    // to enable derived classes to raise the event.
    public virtual void RaiseEventWithArgs()
    {
		for (int i = 0; i < 1; i++)
        // Raise the event in a thread-safe manner using the ?. operator.
        EventWithArgs?.Invoke(this.gu, this.str);
    }
	
	public virtual void RaiseEventNoArgs()
    {
		for (int i = 0; i < 1; i++)
        // Raise the event in a thread-safe manner using the ?. operator.
        	EventNoArgs?.Invoke();
    }
}
```

**Comment by benmwatson** [comment]
@BazookaMusic Take a look at the PR for this I just submitted and let me know what you think.
