### ISSUE TITLE
No releases are created for this repository

### ISSUE THREAD

**Issue by dr4** [Microsoft/Microsoft.IO.RecyclableMemoryStream#13]
This repository does not provide any revisions that are tagged as release: https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/releases

I believe it is worth to:
1) Mark stable version as release
2) Create NuGet package, which version is aligned with github's one

**Comment by doubleyewdee** [comment]
Thanks, we'll take care of that.

**Comment by doubleyewdee** [comment]
We did a 1.1 release for our 1.1 NuGet package push and we'll keep that practice up. Thanks!
