### ISSUE TITLE
Remove System.Runtime.CompilerServices.Unsafe 4.5.2 version constraint

### ISSUE THREAD

**Issue by george-polevoy** [microsoft/Microsoft.IO.RecyclableMemoryStream#130]
The package has a constraint on the System.Runtime.CompilerServices.Unsafe package version, which is too restrictive.

Install failed (..., package: Microsoft.IO.RecyclableMemoryStream v1.4.0) Unable to resolve dependencies. 'System.Runtime.CompilerServices.Unsafe 4.5.2' is not compatible with 'System.Text.Json 4.6.0 constraint: System.Runtime.CompilerServices.Unsafe (>= 4.6.0)'.

**Comment by benmwatson** [comment]
I'll look into it

**Comment by benmwatson** [comment]
Could you please double-check this? RMS does not have any dependencies on any other packages at all. You can see this at [The NuGet page](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/1.4.0) (or by opening the package in something NuGet Package Explorer), or by looking at which assemblies are referenced by the assembly itself. You can also see in the [csproj ](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/master/src/Microsoft.IO.RecyclableMemoryStream.csproj)file that no dependency packages are consumed.

What platform are you using, and which specific target is being consumed by your project?

**Comment by benmwatson** [comment]
Closing this as there has been no response, and it does not appear actionable.
