### ISSUE TITLE
RecyclableMemoryStream is closed after GZip and CryptoStream dispose/close but native MemoryStream not

### ISSUE THREAD

**Issue by dnsoftpl** [microsoft/Microsoft.IO.RecyclableMemoryStream#131]
RecyclableMemoryStream is closed after GZip disposed but MemoryStream don't.  Move  line `return mso.ToArray();` inside using won't work because I receive not completed results (stream is not closed yet). After manual close the same 'object disposed' exception is thrown.

Please consider following code.

`
using Microsoft.IO;
using System.IO;
using System.IO.Compression;

namespace ConsoleApp13
{
    class Program
    {
        private static readonly RecyclableMemoryStreamManager manager = new RecyclableMemoryStreamManager();

        static void Main(string[] args)
        {
            var sourceBuffer = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7 };
            ZipNormalStream(sourceBuffer);
            ZipRecyclableStream(sourceBuffer);
        }

        public static byte[] ZipNormalStream(byte[] bytes)
        {
            using (var msi = new MemoryStream(bytes))
            using (var mso = new MemoryStream())
            {
                using (var gs = new GZipStream(mso, CompressionMode.Compress))
                {
                    msi.CopyTo(gs);
                }

                return mso.ToArray();
            }
        }

        public static byte[] ZipRecyclableStream(byte[] bytes)
        {
            using (var msi = manager.GetStream(bytes))
            using (var mso = manager.GetStream())
            {
                using (var gs = new GZipStream(mso, CompressionMode.Compress))
                {
                    msi.CopyTo(gs);
                }

                return mso.ToArray();
            }
        }
    }
}
`

**Comment by benmwatson** [comment]
This is by design. You need to use the overload of `GZipStream` that takes a `Boolean` to leave the underlying stream open.

It works with `MemoryStream` because `Dispose` doesn't actually do anything and the bytes are still available. When a `RecyclableMemoryStream` is disposed, the bytes are returned to the pool.

See also #127.

**Comment by dnsoftpl** [comment]
Hello thank you for your fast respond. 
For Gzip is working fine.
Unfortunetly we cannot handle StreamWritter together with an Microsoft's example about AES encryption and decryption. 

Please see following adjusted microsoft example 

`using Microsoft.IO;
using NUnit.Framework;
using System;
using System.IO;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Threading;

namespace ConsoleApp13
{
    class Program
    {
        internal const int DefaultBufferSize = 1024;
        private static readonly RecyclableMemoryStreamManager manager = new RecyclableMemoryStreamManager();
        private static volatile Encoding _UTF8NoBOM;

        internal static Encoding UTF8NoBOM
        {
            get
            {
                if (_UTF8NoBOM == null)
                {
                    // No need for double lock - we just want to avoid extra
                    // allocations in the common case.
                    UTF8Encoding noBOM = new UTF8Encoding(false, true);
                    Thread.MemoryBarrier();
                    _UTF8NoBOM = noBOM;
                }
                return _UTF8NoBOM;
            }
        }
        static void Main(string[] args)
        {
            string original = "Here is some data to encrypt!";

            // Create a new instance of the Aes
            // class.  This generates a new key and initialization
            // vector (IV).
            using (Aes myAes = Aes.Create())
            {

                // Encrypt the string to an array of bytes.
                byte[] encrypted = EncryptStringToBytes_Aes(original, myAes.Key, myAes.IV);

                // Decrypt the bytes to a string.
                string roundtrip = DecryptStringFromBytes_Aes(encrypted, myAes.Key, myAes.IV);

                //Display the original data and the decrypted data.
                Console.WriteLine("Original:   {0}", original);
                Console.WriteLine("Round Trip: {0}", roundtrip);

                // Encrypt the string to an array of bytes.
                encrypted = EncryptStringToBytes_Aes__Recyclable_Memory(original, myAes.Key, myAes.IV);

                // Decrypt the bytes to a string.
                roundtrip = DecryptStringFromBytes_Aes_Recyclable_Memory(encrypted, myAes.Key, myAes.IV);

                //Display the original data and the decrypted data.
                Console.WriteLine("Original:   {0}", original);
                Console.WriteLine("Round Trip: {0}", roundtrip);

                Console.ReadKey();
            }
        }


        static byte[] EncryptStringToBytes_Aes(string plainText, byte[] Key, byte[] IV)
        {
            // Check arguments.
            if (plainText == null || plainText.Length <= 0)
                throw new ArgumentNullException("plainText");
            if (Key == null || Key.Length <= 0)
                throw new ArgumentNullException("Key");
            if (IV == null || IV.Length <= 0)
                throw new ArgumentNullException("IV");
            byte[] encrypted;

            // Create an Aes object
            // with the specified key and IV.
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Key;
                aesAlg.IV = IV;

                // Create an encryptor to perform the stream transform.
                ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

                // Create the streams used for encryption.
                using (MemoryStream msEncrypt = new MemoryStream())
                {
                    using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                    {
                        using (StreamWriter swEncrypt = new StreamWriter(csEncrypt))
                        {
                            //Write all data to the stream.
                            swEncrypt.Write(plainText);
                        }
                        encrypted = msEncrypt.ToArray();
                    }
                }
            }

            // Return the encrypted bytes from the memory stream.
            return encrypted;
        }


        static string DecryptStringFromBytes_Aes(byte[] cipherText, byte[] Key, byte[] IV)
        {
            // Check arguments.
            if (cipherText == null || cipherText.Length <= 0)
                throw new ArgumentNullException("cipherText");
            if (Key == null || Key.Length <= 0)
                throw new ArgumentNullException("Key");
            if (IV == null || IV.Length <= 0)
                throw new ArgumentNullException("IV");

            // Declare the string used to hold
            // the decrypted text.
            string plaintext = null;

            // Create an Aes object
            // with the specified key and IV.
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Key;
                aesAlg.IV = IV;

                // Create a decryptor to perform the stream transform.
                ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);

                // Create the streams used for decryption.
                using (MemoryStream msDecrypt = new MemoryStream(cipherText))
                {
                    using (CryptoStream csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read))
                    {
                        using (StreamReader srDecrypt = new StreamReader(csDecrypt))
                        {

                            // Read the decrypted bytes from the decrypting stream
                            // and place them in a string.
                            plaintext = srDecrypt.ReadToEnd();
                        }
                    }
                }
            }

            return plaintext;
        }

        static byte[] EncryptStringToBytes_Aes__Recyclable_Memory(string plainText, byte[] Key, byte[] IV)
        {
            // Check arguments.
            if (plainText == null || plainText.Length <= 0)
                throw new ArgumentNullException("plainText");
            if (Key == null || Key.Length <= 0)
                throw new ArgumentNullException("Key");
            if (IV == null || IV.Length <= 0)
                throw new ArgumentNullException("IV");
            byte[] encrypted;

            // Create an Aes object
            // with the specified key and IV.
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Key;
                aesAlg.IV = IV;

                // Create an encryptor to perform the stream transform.
                ICryptoTransform encryptor = aesAlg.CreateEncryptor(aesAlg.Key, aesAlg.IV);

                // Create the streams used for encryption.
                using (MemoryStream msEncrypt = manager.GetStream())
                {
                    using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
                    {
                        using (StreamWriter swEncrypt = new StreamWriter(csEncrypt, UTF8NoBOM, DefaultBufferSize, true))
                        {
                            //Write all data to the stream.
                            swEncrypt.Write(plainText);
                        }
                        encrypted = msEncrypt.ToArray();
                    }
                }
            }

            // Return the encrypted bytes from the memory stream.
            return encrypted;
        }


        static string DecryptStringFromBytes_Aes_Recyclable_Memory(byte[] cipherText, byte[] Key, byte[] IV)
        {
            // Check arguments.
            if (cipherText == null || cipherText.Length <= 0)
                throw new ArgumentNullException("cipherText");
            if (Key == null || Key.Length <= 0)
                throw new ArgumentNullException("Key");
            if (IV == null || IV.Length <= 0)
                throw new ArgumentNullException("IV");

            // Declare the string used to hold
            // the decrypted text.
            string plaintext = null;

            // Create an Aes object
            // with the specified key and IV.
            using (Aes aesAlg = Aes.Create())
            {
                aesAlg.Key = Key;
                aesAlg.IV = IV;

                // Create a decryptor to perform the stream transform.
                ICryptoTransform decryptor = aesAlg.CreateDecryptor(aesAlg.Key, aesAlg.IV);

                // Create the streams used for decryption.
                using (MemoryStream msDecrypt = manager.GetStream(cipherText))
                {
                    using (CryptoStream csDecrypt = new CryptoStream(msDecrypt, decryptor, CryptoStreamMode.Read))
                    {
                        using (StreamReader srDecrypt = new StreamReader(csDecrypt))
                        {

                            // Read the decrypted bytes from the decrypting stream
                            // and place them in a string.
                            plaintext = srDecrypt.ReadToEnd();
                        }
                    }
                }
            }

            return plaintext;
        }
    }
}
`

**Comment by benmwatson** [comment]
Both `CryptoStream` and `StreamWriter` have constructors that take the same `Boolean` to leave the underlying stream open. Or is there a separate issue going on? Please elaborate.

**Comment by dnsoftpl** [comment]
There is another issue. It seems like it works in incorrect way if we leave streams open. Please see following error
![image](https://user-images.githubusercontent.com/11705751/107916118-09ff3680-6f66-11eb-834e-f0555a903125.png)

**Comment by benmwatson** [comment]
I'm not sure what's going on here, but this seems more like a problem with using the crypto APIs, then something related to streams specifically. Have you reviewed their documentation carefully and looked at other examples? I think further help on this is probably out of scope for a RMS discussion. If you can produce a repro that works for MS, breaks on RMS, and follows the leaveOpen guidelines I gave above, I'll be more than happy to look into it.

**Comment by cbersch** [comment]
@dnsoftpl You'll find the answer in the [`CryptoStream` source code, line 107ff](https://source.dot.net/#System.Security.Cryptography/System/Security/Cryptography/CryptoStream.cs,107).
When encrypting to a `MemoryStream`, or equally a `RecyclableMemoryStream`, you must call `FlushFinalBlock()` before you can access the full encrypted data with `ToArray()`

    using (MemoryStream msEncrypt = manager.GetStream())
    {
        using (CryptoStream csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write))
        {
            using (StreamWriter swEncrypt = new StreamWriter(csEncrypt, UTF8NoBOM, DefaultBufferSize, true))
            {
                //Write all data to the stream.
                swEncrypt.Write(plainText);
            }
            csEncrypt.FlushFinalBlock();
            encrypted = msEncrypt.ToArray();
        }
    }
