### ISSUE TITLE
Cannot derive from sealed type 'RecyclableMemoryStream'

### ISSUE THREAD

**Issue by NateRadebaugh** [microsoft/Microsoft.IO.RecyclableMemoryStream#136]
This library advertises itself as a drop-in replacement for Stream, but is marked as `sealed`, which means I cannot create a
```cs
internal class ReadOnlyStream: Microsoft.IO.RecyclableMemoryStream
```

Since there is no `IStream` interface to be implemented, we'll need a more meaningful refactor to migrate from `Stream` to `RecyclableMemoryStream`.

**Comment by benmwatson** [comment]
Closing because the related PR was closed.
