### ISSUE TITLE
CopyToAsync reset source stream position

### ISSUE THREAD

**Issue by m-valenta** [microsoft/Microsoft.IO.RecyclableMemoryStream#139]
We found strange behaviour change between 1.4.0 and previous version at **CopyToAsync** method. At version 1.4.0 this method reset (IMO unexpectedly) the SOURCE stream position back to position before call.

**Comment by benmwatson** [comment]
Please see the release notes for v1.4.0. The previous behavior was a bug. https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/releases/tag/1.4.0

**Comment by m-valenta** [comment]
No, this is different thing (marked line). 
![image](https://user-images.githubusercontent.com/40561145/110352760-96b58580-8036-11eb-829e-f9ab9ac8de78.png)

**Comment by m-valenta** [comment]
You can compare marked behaviour with MemoryStream...

**Comment by benmwatson** [comment]
ah, got it. Will take a look.
