### ISSUE TITLE
Documentation suggestion - lighten up on the "ToArray() is always considered a bug" thing

### ISSUE THREAD

**Issue by jeffska** [microsoft/Microsoft.IO.RecyclableMemoryStream#148]
While I definitely agree that calling ToArray() should generally be avoided, there are at least some cases where using it with RecyclableMemoryStream makes sense. Namely using RMS as a temp stream/buffer for compression/decompression when the result must be a properly sized array. Such as

```c#
using var ms = SharedMemoryStreamManager.GetStream();
using var gzip = new GZipStream(inbytes, CompressionMode.Decompress);
gzip.CopyTo(ms);
return ms.ToArray();
```

Using RMS for this can avoid heap allocation for temporary use, which is a very good thing. Even if it still ends up needing to allocate and copy the final result. Maybe a provide a counter-example like this in the docs?

**Comment by benmwatson** [comment]
Fair enough. I can change the docs to be a little less heavy handed, while still communicating that you are incurring GC pressure.
