### ISSUE TITLE
Allow multiple Dispose calls OR expose Disposed state

### ISSUE THREAD

**Issue by EnCey** [Microsoft/Microsoft.IO.RecyclableMemoryStream#15]
A `MemoryStream` can be disposed twice or multiple times, but the `RecyclableMemoryStream` throws an exception. 

Consider this example:
```csharp
var stream = storage.MemoryStreamManager.GetStream();
blob.DownloadToStream(stream); // may throw a StorageException
using (var reader = new StreamReader(stream, Encoding.UTF8)) {
	// read data
}
```
Here, the `stream` should be disposed if `DownloadToStream` fails. However, when put in a `using` block, an exception will be raised when the `reader` is disposed (and configured to close the underlying stream, which is the default). 

According to the [`Dispose` docs](https://msdn.microsoft.com/en-us/library/system.idisposable.dispose.aspx) disposing multiple times should be allowed: 
> If an object's Dispose method is called more than once, the object must ignore all calls after the first one. The object must not throw an exception if its Dispose method is called multiple times. Instance methods other than Dispose can throw an ObjectDisposedException when resources are already disposed.

Alternatively the `disposed` field could be exposed with a property to allow for explicit checks:
```csharp
var stream = storage.MemoryStreamManager.GetStream();
try {... } finally { if (!stream.Disposed) stream.Dispose() }
```
... although supporting multiple `Dispose` calls would be more convenient and less clunky.

**Comment by dr4** [comment]
Hi @EnCey,

This issue is already fixed in [#9](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/commit/56367f0c56948d8b47de1911ab68cb750ee4e87d)

But unfortunately, NuGet package was not updated.
Seems like you have to reuse the latest code version from GitHub in your project

**Comment by EnCey** [comment]
Oh man, didn't check the closed issues. Sorry!
Thanks for the heads up @dr4

**Comment by doubleyewdee** [comment]
We'll be releasing a NuGet update as soon as I can get a handle on getting the binaries properly signed (it is sadly pretty non-trivial)

Date: Tue, 28 Apr 2015 08:32:17 -0700

**Comment by EnCey** [comment]
@doubleyewdee any updates on when the NuGet update will come?

**Comment by doubleyewdee** [comment]
Hey sorry! Working on the code sign stuff. Will try and wrap it this week with a 1.0.1 rev

Date: Tue, 12 May 2015 01:30:02 -0700

**Comment by damianh** [comment]
+1 just got bitten by this. Particularly when someone else's `StreamReader` closes it on my behalf.

**Comment by EnCey** [comment]
Well, it took a while but it works now ;) 
Thanks for the update!
