### ISSUE TITLE
RecyclableMemoryStream with dependency injection

### ISSUE THREAD

**Issue by LewisWong** [microsoft/Microsoft.IO.RecyclableMemoryStream#150]
Hi,

This is more of a usage question than an issue.

I have an aspnetcore application, is it ok to register `RecyclableMemoryStreamManager` as singleton with `IServiceCollection` so I can use the leverage constructor injection to the classes where I need to use the stream manager?

Many Thank,
Lewis

**Comment by benmwatson** [comment]
I don't know if I can speak to a very particular scenario, but I can answer in general: 

`RecyclableMemoryStreamManager` can be used a singleton and is thread safe, so it should be easily passed around and used safely in most scenarios.
