### ISSUE TITLE
Seeing incorrect values for largePoolInUseBytes  in MemoryStreamNewLargeBufferCreated Event

### ISSUE THREAD

**Issue by cryolithic** [microsoft/Microsoft.IO.RecyclableMemoryStream#153]
I'm seeing odd results in the ETL capture. The requiredSize is correct, however right after the first event. No NonPooled events are produced.

Maximum buffer size is 2GB with the multiple set to 100MB.

I haven't had a chance to fire this up in the debugger yet, but reading through the source, the cause isn't jumping out at me.

I'll try and pop it up in the debugger in the next few days if I have time.

| Event Name                        | Time MSec  | Process Name  | requiredSize  | largePoolInUseBytes        |
| --------------------------------------------------------------------- | ---------- | ------------- | ------------- | -------------------------- |
| MemoryStreamNewLargeBufferCreated | 5045.581   |    (8320)     | 1,048,576,000 |      0                     |
| MemoryStreamNewLargeBufferCreated | 10063.866  |    (8320)     | 838,860,800   | 4,503,599,627,370,496,000  |
| MemoryStreamNewLargeBufferCreated | 14169.562  |    (8320)     | 419,430,400   | 8,106,479,329,266,892,800  |
| MemoryStreamNewLargeBufferCreated | 17953.344  |    (8320)     | 419,430,400   | -8,538,824,893,494,460,416 |
| MemoryStreamNewLargeBufferCreated | 43100.350  |    (8320)     | 314,572,800   | -6,737,385,042,546,262,016 |
| MemoryStreamNewLargeBufferCreated | 48647.374  |    (8320)     | 419,430,400   | -5,386,305,154,335,113,216 |
| MemoryStreamNewLargeBufferCreated | 74215.593  |    (8320)     | 838,860,800   | -3,584,865,303,386,914,816 |
| MemoryStreamNewLargeBufferCreated | 78405.369  |    (8320)     | 1,048,576,000 | 18,014,398,509,481,984     |
| MemoryStreamNewLargeBufferCreated | 93225.156  |    (8320)     | 419,430,400   | 4,521,614,025,879,977,984  |
| MemoryStreamNewLargeBufferCreated | 95370.284  |    (8320)     | 419,430,400   | 6,323,053,876,828,176,384  |
| MemoryStreamNewLargeBufferCreated | 97056.637  |    (8320)     | 419,430,400   | 8,124,493,727,776,374,784  |
| MemoryStreamNewLargeBufferCreated | 104310.556 |    (8320)     | 419,430,400   | -8,520,810,494,984,978,432 |
| MemoryStreamNewLargeBufferCreated | 118277.949 |    (8320)     | 419,430,400   | -6,719,370,644,036,780,032 |
| MemoryStreamNewLargeBufferCreated | 139880.781 |    (8320)     | 419,430,400   | -4,917,930,793,088,581,632 |
| MemoryStreamNewLargeBufferCreated | 165635.430 |    (8320)     | 943,718,400   | -3,116,490,942,140,383,232 |
| MemoryStreamNewLargeBufferCreated | 170262.082 |    (8320)     | 943,718,400   | 936,748,722,493,063,168    |
| MemoryStreamNewLargeBufferCreated | 175780.791 |    (8320)     | 838,860,800   | 4,989,988,387,126,509,568  |
| MemoryStreamNewLargeBufferCreated | 180518.711 |    (8320)     | 314,572,800   | 8,592,868,089,022,906,368  |
| MemoryStreamNewLargeBufferCreated | 182051.932 |    (8320)     | 419,430,400   | -8,502,796,096,475,496,448 |
| MemoryStreamNewLargeBufferCreated | 184888.932 |    (8320)     | 314,572,800   | -6,701,356,245,527,298,048 |
| MemoryStreamNewLargeBufferCreated | 186491.190 |    (8320)     | 419,430,400   | -5,350,276,357,316,149,248 |
| MemoryStreamNewLargeBufferCreated | 191728.155 |    (8320)     | 419,430,400   | -8,052,436,133,738,446,848 |
| MemoryStreamNewLargeBufferCreated | 230333.452 |    (8320)     | 1,048,576,000 | -5,350,276,357,316,149,248 |

**Comment by benmwatson** [comment]
Yeah, that looks like a bad value for sure. I will try to get to this in the next week. I'm in a bit of a crunch, so have been ignoring RMS for a few weeks.

**Comment by benmwatson** [comment]
I have tried reproing this in a unit test and cannot. The code is also fairly straightforward and I don't see an obvious bug. Were you able to debug it?

Can you share the full ETL file with me? It would be useful to see all events for context.

What are you using to capture the events?

**Comment by grbell-ms** [comment]
This smells like and endianness bug or something similar.  `(1_048_576_000L << 32) == 4_503_599_627_370_496_000`

**Comment by benmwatson** [comment]
Ok, that's interesting. @cryolithic what kind of system are you running on?

There's no bit shifting in the RMS code directly...maybe some bug in ETW or CLR?

**Comment by cryolithic** [comment]
I'm running on server 2016, under VMware.

Capturing with perfview. 

Not sure about endianness, but I was unable to repro on my local machine in the debugger, so something could be performing a shift somewhere

**Comment by Fradulentus** [comment]
Здравствуйте, я могу поучаствовать в обсуждении данного вопроса?

**Comment by Fradulentus** [comment]
> Да, это выглядит как плохое значение наверняка. Я постараюсь добраться до этого на следующей неделе. Я в немного кризиса, так что были игнорируя RMS в течение нескольких недель.

> Вы обращаетесь в облачную службу Microsoft Corp,
   
С чего начнем?

**Comment by Fradulentus** [comment]
> Я попытался reproing это в единицу теста и не может. Код также довольно прост, и я не вижу очевидной ошибки. Удалось ли вам отладить его?
> 
> Можете ли вы поделиться полным файлом ETL со мной? Было бы полезно, чтобы все события для контекста.
> 
> Что вы используете для захвата событий?

> Вы обращаетесь в облачную службу Microsoft Corp,
    Для чего вам именно необходим сам файл, обсуждая проблему?

**Comment by benmwatson** [comment]
@Fradulentus I translated your text to English with Microsoft Translator, but I'm not sure your comments are on-topic for this. Do you have a proposed fix for this or know something about it?

**Comment by benmwatson** [comment]
> I'm running on server 2016, under VMware.
> 
> Capturing with perfview.
> 
> Not sure about endianness, but I was unable to repro on my local machine in the debugger, so something could be performing a shift somewhere

Can you check the endianness of the VM? Is it running on or simulating a non-x64 chip?

**Comment by Fradulentus** [comment]
> @Fradulentus Я 
> @cryolithic

**Comment by cryolithic** [comment]
> > I'm running on server 2016, under VMware.
> > Capturing with perfview.
> > Not sure about endianness, but I was unable to repro on my local machine in the debugger, so something could be performing a shift somewhere
> 
> Can you check the endianness of the VM? Is it running on or simulating a non-x64 chip?

Nothing weird there. It's bog standard Sandy Bridge level virtualization. I'm certain of that as I had to argue to update it from Westmere compatibility.

I'm about to include as source rather than assembly, as I want to test a few things. I'll let you know if I see a discrepancy there.

**Comment by cryolithic** [comment]
I also see that I'm running 1.3.6. I'll update to 2.0 and see what's what there.

**Comment by cryolithic** [comment]
Running with 2.0 seems to be fine on my dev box.  
### Works On My Machine (TM). 

Close it up, and if I see anything odd again, I'll comment.

requiredSize="408,371,200" largePoolInUseBytes="408,371,200"
requiredSize="408,371,200" largePoolInUseBytes="816,742,400"
requiredSize="695,500,800" largePoolInUseBytes="1,512,243,200"
requiredSize="988,057,600" largePoolInUseBytes="2,500,300,800"
requiredSize="440,012,800" largePoolInUseBytes="2,940,313,600"
requiredSize="408,371,200" largePoolInUseBytes="3,348,684,800"
requiredSize="988,057,600" largePoolInUseBytes="4,336,742,400"
requiredSize="440,012,800" largePoolInUseBytes="4,776,755,200"
requiredSize="440,012,800" largePoolInUseBytes="5,216,768,000"
requiredSize="988,057,600" largePoolInUseBytes="6,204,825,600"
requiredSize="695,500,800" largePoolInUseBytes="6,900,326,400"
requiredSize="415,744,000" largePoolInUseBytes="7,316,070,400"
requiredSize="987,955,200" largePoolInUseBytes="8,304,025,600"
requiredSize="408,371,200" largePoolInUseBytes="8,712,396,800"
requiredSize="695,398,400" largePoolInUseBytes="9,407,795,200"
requiredSize="440,012,800" largePoolInUseBytes="9,847,808,000"
requiredSize="988,057,600" largePoolInUseBytes="10,835,865,600"
requiredSize="988,057,600" largePoolInUseBytes="11,823,923,200"
requiredSize="408,371,200" largePoolInUseBytes="12,232,294,400"
requiredSize="987,955,200" largePoolInUseBytes="12,811,878,400"
requiredSize="987,750,400" largePoolInUseBytes="12,779,929,600"
requiredSize="695,500,800" largePoolInUseBytes="12,487,372,800"

**Comment by Fradulentus** [comment]
Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows 10

От: ***@***.***>
Отправлено: 21 апреля 2021 г. в 21:24
Кому: ***@***.***>
Копия: ***@***.***>; ***@***.***>
Тема: Re: [microsoft/Microsoft.IO.RecyclableMemoryStream] Seeing incorrect values for largePoolInUseBytes in MemoryStreamNewLargeBufferCreated Event (#153)


Running with 2.0 seems to be fine on my dev box.

Works On My Machine (TM).

Close it up, and if I see anything odd again, I'll comment.

requiredSize="408,371,200" largePoolInUseBytes="408,371,200"
requiredSize="408,371,200" largePoolInUseBytes="816,742,400"
requiredSize="695,500,800" largePoolInUseBytes="1,512,243,200"
requiredSize="988,057,600" largePoolInUseBytes="2,500,300,800"
requiredSize="440,012,800" largePoolInUseBytes="2,940,313,600"
requiredSize="408,371,200" largePoolInUseBytes="3,348,684,800"
requiredSize="988,057,600" largePoolInUseBytes="4,336,742,400"
requiredSize="440,012,800" largePoolInUseBytes="4,776,755,200"
requiredSize="440,012,800" largePoolInUseBytes="5,216,768,000"
requiredSize="988,057,600" largePoolInUseBytes="6,204,825,600"
requiredSize="695,500,800" largePoolInUseBytes="6,900,326,400"
requiredSize="415,744,000" largePoolInUseBytes="7,316,070,400"
requiredSize="987,955,200" largePoolInUseBytes="8,304,025,600"
requiredSize="408,371,200" largePoolInUseBytes="8,712,396,800"
requiredSize="695,398,400" largePoolInUseBytes="9,407,795,200"
requiredSize="440,012,800" largePoolInUseBytes="9,847,808,000"
requiredSize="988,057,600" largePoolInUseBytes="10,835,865,600"
requiredSize="988,057,600" largePoolInUseBytes="11,823,923,200"
requiredSize="408,371,200" largePoolInUseBytes="12,232,294,400"
requiredSize="987,955,200" largePoolInUseBytes="12,811,878,400"
requiredSize="987,750,400" largePoolInUseBytes="12,779,929,600"
requiredSize="695,500,800" largePoolInUseBytes="12,487,372,800"
