### ISSUE TITLE
Add default instance

### ISSUE THREAD

**Issue by LIFEfreedom** [microsoft/Microsoft.IO.RecyclableMemoryStream#155]
Maybe you should add the default instance like `ArrayPool<T>.Shared`?
The naming syntax will be as follows: `RecyclableMemoryStreamManager.DefaultInstance`

**Comment by LIFEfreedom** [comment]
I found a [closed discussion](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/issues/38), then you decided not to add this functionality, maybe something has changed now?

**Comment by benmwatson** [comment]
The RMSManager ctor requires a number of arguments that dramatically change the memory footprint and behavior of a calling application. I think providing a default instance would be dangerous. There is no good set of reasonable defaults for everyone. This project is used in thousands of projects from small desktop apps up to large portions of Microsoft infrastructure. Those requirements are very different.

**Comment by LIFEfreedom** [comment]
Maybe in this case add static options that will be similar to the parameters in the constructor.
This will allow you to set these options in program.cs (or another application entry point) and use the default static instance throughout your program.
If different pool parameters are needed in different places, then separate instances will be created.
The default instance will be more suitable for the same type of pools throughout the program

**Comment by benmwatson** [comment]
It would be easy enough to add a static accessor like this in end-user own code. I don't think this needs to be baked in.

**Comment by LIFEfreedom** [comment]
Thanks!
