### ISSUE TITLE
CS0012 on xamarinmac20 Tartget

### ISSUE THREAD

**Issue by workgroupengineering** [microsoft/Microsoft.IO.RecyclableMemoryStream#158]
## Current behavior
When using RecyclableMemoryStream in a Tartget target project, the compiler reports the following errors:

```
CS0012	The type 'MemoryStream' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

## Aspected behavior

should compile without errors.

## Environment:
Visual Studio: Visual Studio Community 2019 Build 16.9.4+31205.134
RecyclableMemoryStream  Version: [2.0.0](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/releases/tag/2.0.0)

**Comment by paulomorgado** [comment]
Have you tried adding a reference to `netstandard 2.1.0.0`, as suggested?

**Comment by workgroupengineering** [comment]
I edited the project file as you suggested and now it works.

I think it is better to add targets to library without adding trick.

```xml
<Project Sdk="MSBuild.Sdk.Extras" ToolsVersion="15.0">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;xamarinmac20;xamarinios10;MonoAndroid11.0;MonoAndroid10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Memory" Version="4.5.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.0.0" />    
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'xamarinmac20'">    
    <Reference Include="netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"/>
  </ItemGroup>


</Project>
```

**Comment by paulomorgado** [comment]
This is not a trick. This is how it works.

You can get the same for .NET Standard on other targets.

Adding those targets to the library is not the solution. Otherwise, we should add them all. That's what .NET Standard is for. To avoid all that.

**Comment by workgroupengineering** [comment]
Hi, I think it is a trick because adding the reference is not possible from the ide and only those who know a little about how msbuild ItemGroup work can solve it easily.

**Comment by workgroupengineering** [comment]
Microsoft Visual Studio Community 2019
Version 16.9.4

![immagine](https://user-images.githubusercontent.com/12531229/117642327-71084200-b187-11eb-860b-d03600b746c0.png)

**Comment by paulomorgado** [comment]
You should report that through "Report a problem".
