### ISSUE TITLE
Should Return Blocks etc be internal?

### ISSUE THREAD

**Issue by gregoryyoung** [Microsoft/Microsoft.IO.RecyclableMemoryStream#16]
The manager by itself can be quite a useful thing without using streams. An example use case could be reusing buffers with socket io.

**Comment by doubleyewdee** [comment]
The two are currently fairly tied together so I'm hesitant to make any big changes here. What might be interesting is a third type encompassing most of the manager that does expose buffer management publicly. It's not something I'm looking to do at this time but I'd be happy to look at any PRs and reopen this.
