### ISSUE TITLE
net 4.72  Span and net standard 2.1 

### ISSUE THREAD

**Issue by stefan2410** [microsoft/Microsoft.IO.RecyclableMemoryStream#162]
Hi,  I'm forced to use .Net 4.72 till end of year.
I want to write in a RecycableMemoryStream this 

          Span<byte> byteArray = new Span<byte>((byte*)buffer.ToPointer(),length);
           stream.Write(byteArray, 0, length);
           
  The Span with System.Buffers works, but I don't have interface for the stream.write
  In the code I can see it the IBufferWrite is enabled for the .Net Standard 2.1 
  Any way to do it in my configuration ?

**Comment by benmwatson** [comment]
I'll look into this. It might not be a hard change.

**Comment by stefan2410** [comment]
Thanks a lot @benmwatson
