### ISSUE TITLE
"Inheritance security rules violated while overriding member" on .Net Framwork 4.8

### ISSUE THREAD

**Issue by johnfedak** [microsoft/Microsoft.IO.RecyclableMemoryStream#168]
This appears to be a 2.1 regression

1) Create a new 4.8 project
2) Add v2.1 RMS package via NuGet
3) Simply call RecyclableMemoryStreamManager.GetStream()

        static void Main(string[] args) {
            RecyclableMemoryStreamManager manager = new RecyclableMemoryStreamManager();
            manager.GetStream();
        }   
        
       
System.TypeLoadException
  HResult=0x80131522
  Message=Inheritance security rules violated while overriding member: 'Microsoft.IO.RecyclableMemoryStream.Advance(Int32)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.
  Source=Microsoft.IO.RecyclableMemoryStream
  StackTrace:
   at Microsoft.IO.RecyclableMemoryStreamManager.GetStream() in /_/src/RecyclableMemoryStreamManager.cs:line 709
   at RmsTest.Program.Main(String[] args) in C:\Users\fedak\source\repos\RmsTest\RmsTest\Program.cs:line 13

**Comment by quynh-ng** [comment]
I've got the same issue too

**Comment by benmwatson** [comment]
Will take a look.
