### ISSUE TITLE
memory cache question

### ISSUE THREAD

**Issue by stefan2410** [microsoft/Microsoft.IO.RecyclableMemoryStream#170]
Hi, I would like to understand better the caching behavior fo RecycableMemoryManager
After we dispose the streams  MM keeps them in memory (probably if they can fit) and return them at first request  (without cleanzing) . This is my understanding, hopefully correct.
Question: if we have a very big stream (e.g. ~500 MB) and many others with much smaller size,
 Is there a parameter to instruct  MM  keeping in memory only the streams with a maximum given size?

**Comment by benmwatson** [comment]
There is no way to manage streams individually by size, but I think through clever manipulation of the parameters, you can choose to keep only the streams you want in the pool. The ReadMe.Md file contains more information about RMS's memory management works.

**Comment by stefan2410** [comment]
I don't want to  to manage streams individually by size.  For example, what parameters I should give in order to keep in memory streams less than 50 MB aproximately ?
int blockSize = 1024;      can take less  that 1024 ? or there is lower limit of 1024? right now I use it with smaller size.
int largeBufferMultiple = 1024 * 1024;
int maxBufferSize = 16 * largeBufferMultiple;

var manager = new RecyclableMemoryStreamManager(blockSize, 
                                                largeBufferMultiple, 
                                                maxBufferSize);

manager.GenerateCallStacks = true;
manager.AggressiveBufferReturn = true;
**manager.MaximumFreeLargePoolBytes = maxBufferSize * 3;**
manager.MaximumFreeSmallPoolBytes = 100 * blockSize;

**Comment by benmwatson** [comment]
The property `manager.MAximumFreeLargePoolBytes` refers to the total bytes allowed to exist in the free pool. It is not per-stream.

>what parameters I should give in order to keep in memory streams less than 50 MB aproximately 

Note that the parameter only control how much memory is allowed to sit unused in the pool. It does not control how many bytes you might have in-use. That kind of thing is up to your program to decide. The memory manager will attempt to satisfy all allocation requests because it's not trying to manage all of your program's memory usage, just how much data can be in its pool. 

For example, if you set `manager.MaximumFreeLargePoolBytes` to around 50MB, you are still free to call `manager.GetStream` until you exhaust available physical memory. It's only when you start disposing, and the buffers go back into the pool that it will start dropping buffers once the 50 MB limit is reached.

**Comment by stefan2410** [comment]
@benmwatson   I should rephrase my question. 
 I asked if there was a  parameter so streams bigger than a configurable size, when they would be disposed to be freed also from the pool. 
 The manager.MAximumFreeLargePoolBytes  as I understand (with your help)  is the total bytes. This can be a big number in my case,  e.g. 5-6 GB RAM.  If I've understood you well, this is very useful.
 But  my case has also another characteristic. Lets say the  80% of the streams are under 20 GB , repeatedly, re-allocated  
 and 20%  are bigger - not often-  and some-rare-  are very big. e..g. > 600 GB.   
 So is there a way  to configure the MemoryManager to drop these big streams ?
 Or manually before our dispose to instruct the MM to drop them from the pool?
 Should such proposed tactique has memory management benefits, as I understand it, 
 or it is not significant and am not right on this?

**Comment by benmwatson** [comment]
Ok, I think I understand you. There might be a way to do what you want--it depends on how you look at it. If you pass your `maxBufferSize` value from above to the appropriate `RecyclableMemoryStreamManager` constructor, then that will cap your large buffer pool at 16 MB buffers. You can still allocate streams larger than this, but the buffers will not be pooled, so if a stream grows to 600MB AND it is converted from the chained blocks into a single large contiguous buffer, that buffer will never be pooled. 

The important thing is here that it's the buffers that are pooled, not the streams. So if you have tons of small-pool blocks hanging around, you can chain those all day long into a huge stream. If you never convert that to a single large-pool buffer (via `GetBuffer`) then all of those blocks can be re-pooled (assuming there is space for them). Once you convert to large-pool buffer, then if it's larger than `maxBufferSize`, it will be dropped and fed to the GC at dispose time.

**Comment by stefan2410** [comment]
Now I understand it better   
`The important thing is here that it's the buffers that are pooled, not the streams. `
The` maxBufferSize` is important .  16 MB buffers are fine to be re-pooled.  No need  to a single large-pool buffer .
As long as the `manager.MaximumFreeLargePoolBytes`   does not exceed the limit, we set e.g. 5 GB.
Every new stream with GetStream will start with a 16 MB buffer, I assume. If it is like that, it is fine to me.
