### ISSUE TITLE
"Collection was modified" exception 

### ISSUE THREAD

**Issue by onionhammer** [microsoft/Microsoft.IO.RecyclableMemoryStream#172]
Getting this exception when disposing a stream that was retrieved from the recyclable memory stream manager, in the context of about 100 parallel threads

Version: 2.1.1

Stack trace:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
  at Microsoft.IO.RecyclableMemoryStreamManager.ReturnBlocks(ICollection`1 blocks, Guid id, String tag) in /_/src/RecyclableMemoryStreamManager.cs:568
  at Microsoft.IO.RecyclableMemoryStream.Dispose(Boolean disposing) in /_/src/RecyclableMemoryStream.cs:357
```

**Comment by benmwatson** [comment]
You likely have two threads trying to dispose of the same stream simultaneously. That is not something supported by the library. Per-Stream APIs are inherently not thread-safe.

Can you verify this by logging each stream's Id property before you dispose it?

**Comment by onionhammer** [comment]
@benmwatson The code using the stream is async; is that not allowed?

i.e.

```C#
async Task<T> InsertSomethingAsync(T item)
{
            using var ms = MyStreamManager.GetStream();
            using (var sw = new Utf8JsonWriter(ms))
                JsonSerializer.Serialize(sw, item, JsonExtensions.JsonOptions);

            ms.Position = 0;

            using var response = await Container.UpsertItemStreamAsync(ms,
                new (partitionKey),
                DefaultRequestOptions);

            response.EnsureSuccessStatusCode();

            return item;
}

```

**Comment by benmwatson** [comment]
I don't know what's happening in `Container.UpsertItemStreamAsync`, so it's hard to say if this is valid. You can certainly use RMS in async code--you just can't manipulate the stream from multiple threads simultaneously. 

The stack above is missing who is calling `Dispose`. The code example also doesn't explicitly dispose of the stream. It might be implicitly disposed by `Ut8JsonWriter`--you'd have to look and see if disposing that writer disposes the underlying stream. That's a common pattern. But if it were disposed by Utf8JsonWriter, then you wouldn't be able to set the `Position` or otherwise access it after disposal. So that's probably fine. 

But from the stack it looks like that while it's disposing the stream, some other thread came along and changed the size of the stream.

You should be able to debug this using the ETW events to log the various operations and see which ones are unexpected.

**Comment by onionhammer** [comment]
@benmwatson Utf8JsonWriter doesn't dispose, and "using var stream" syntax will dispose when it goes out of scope. `UpsertItemAsync` is using Microsoft Cosmos SDK.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/56aa5338d44ffd19ce61b264b24dd16d46df6477/Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs#L210

You say the stream API is inherently *not* threadsafe, so perhaps the blame is with azure-cosmos-dotnet-v3. 

I've worked around the issue by completely removing this library and providing the method with a 'new MemoryStream()'.

**Comment by benmwatson** [comment]
Sorry, I completely ignored the `using var ms` line--that could definitely be the problem. Could you try explicitly expanding the scope of ms's using statement like this:

```
using var ms = MyStreamManager.GetStream();
            using (var sw = new Utf8JsonWriter(ms))
{
                JsonSerializer.Serialize(sw, item, JsonExtensions.JsonOptions);

            ms.Position = 0;

            using var response = await Container.UpsertItemStreamAsync(ms,
                new (partitionKey),
                DefaultRequestOptions);

            response.EnsureSuccessStatusCode();

            return item;
}
```

**Comment by benmwatson** [comment]
@onionhammer Were you able to figure out how the simultaneous access was occurring?

**Comment by onionhammer** [comment]
@benmwatson Nope. The cosmos team basically said

> The Cosmos DB SDK is thread safe and does operations concurrently. It does not matter if AllowBulkExection is enabled or disabled. Having it enabled just causes this scenario to appear more frequently. The memory stream pool library needs to be thread safe or it will result in these type of exception. From my understanding RecyclableMemoryStream is not thread safe.

**Comment by benmwatson** [comment]
Ok, I don't know what to say. It's just fundamentally not allowed to manipulate the stream in more than one thread at a time. It's pretty baked into the design of this library. I suspect it works for regular MemoryStream because Dispose doesn't really do anything.

**Comment by benmwatson** [comment]
Closing because this does not appear to be an issues with RMS per se, but only in how it is used.
