### ISSUE TITLE
SmallPoolInUseSize, SmallPoolFreeSize

### ISSUE THREAD

**Issue by stefan2410** [microsoft/Microsoft.IO.RecyclableMemoryStream#176]
Version 2.1.2
I'm very confused with the metrics of SmallPoolInUseSize, SmallPoolFreeSize.
1st example:   

           int blockSize = 128000;
           long maximumFreeSmallPoolBytes =32000 * ((long)blockSize);
           ....
           this.StreamManager = new RecyclableMemoryStreamManager(blockSize, largeBufferMultiple, maxBufferSize,
                                                   maximumFreeSmallPoolBytes,  maximumFreeLargePoolBytes );

           MemoryStream fillStream = this.StreamManager.GetStream("pool", requiredSize:128000, asContiguousBuffer: true);
            // I got the same results in metrics  either with asContiguousBuffer: true  or false.
            byte[] block1=new byte[128000];
                   for (int i=0; i< 24000; i++)
                   fillStream.Write(block1, 0, 128000);
                   fillStream.Dispose();
                   

 Results: 
    StreamManager.SmallPoolInUseSize :  4,294,967,296   SmallPoolFreeSize: 3,072,000,000 SmallBlocksFree: 24000
    The SmallPoolFreeSize is correct.  What is this SmallPoolInUseSize :  4,294,967,296 ? 
    _The UInt32.MaxValue is 4,294,967,295. coincidence_?     The SmallPoolInUseSize is long.
    Also,maximumFreeSmallPoolBytes should be 4,096,000,000
    
   2nd example: (in production server)
   
               maximumFreeSmallPoolBytes =24,000 * 128,000; //3,072,000,000
               
 Streams are allocated with initial capacity requiredSize:128000, asContiguousBuffer: false
 I know that,  during the day,  they have reached the maximumFreeSmallPoolBytes and work fine.
 I get 
    
            SmallPoolFreeSize 2,854,144,000 SmallPoolInUseSize 217,856,000  //2,854,144,000 + 217,856,000 = 3,072,000,000 
            
   The 2nd example is correct.  What happened in the 1st example ?

**Comment by stefan2410** [comment]
@benmwatson 
The issue seems to happen, after the Stream.Dispose()
 
       long maximumFreeSmallPoolBytes =32000 * 128000; //4096000000
       // initialize StreamManager
       byte[] block1=new byte[128000];
        long test1 = 4096000000;
         int test2 = 128000;             
                for (int i=0; i< 32000; i++)
                {
                    fillStream.Write(block1,0, 128000);
                    Interlocked.Add(ref test1, -test2); 
                }             
              //  test1 = 0
              // this.StreamManager.SmallPoolInUseSize = 4096000000            
               fillStream.Dispose();
               //this.StreamManager.SmallPoolInUseSize = 4294967296

I want to deploy it in production, but I'm afraid of side-effects.

**Comment by benmwatson** [comment]
I will take a look, but probably next week.

**Comment by benmwatson** [comment]
@stefan2410 I've confirmed this is a bug and have a fix in PR #187
