### ISSUE TITLE
Add native GitHub security and versioning dependency alerts

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/Microsoft.IO.RecyclableMemoryStream#177]
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by paulomorgado** [comment]
Is there a way to configure dependabot to only send PRs for vulnerable dependencies?

This is a library and intends to serve the most customers as possible. As long as a library has all the needed features, there's no need to force a dependency on newer versions.

**Comment by aleks-ivanov** [comment]
@paulomorgado Yes.

For **dependency security vulnerabilities scanner and vulnerable dependency update PRs bot**, [enable "Dependabot alerts" and "Dependabot security updates"](https://docs.github.com/en/github/managing-security-vulnerabilities/configuring-dependabot-security-updates).

The `dependabot.yml` automatically enables only Dependabot's dependency **versioning scanner and dependency update PRs bot**.
