### ISSUE TITLE
Are the event invocations inside RecyclableMemoryStreamManager susceptible to race conditions?

### ISSUE THREAD

**Issue by stakx** [Microsoft/Microsoft.IO.RecyclableMemoryStream#19]
I noticed that `RecyclableMemoryStreamManager` raises events in the following manner:

```cs
if (this.BlockCreated != null)
{
    this.BlockCreated();
}
```

which appears to be susceptible to a race condition: what if another thread unsubscribes the last handler from the event just before the invocation, but after the null check? Since the buffer manager class is supposed to be thread-safe, this should probably be fixed.

In his book "CLR via C#" (see pp. 264-265 in the 3rd edition), Jeffrey Richter recommends the following pattern for safely raising an event:

```cs
EventHandler blockCreated = Interlocked.CompareExchange(ref this.BlockCreated, null, null);
if (blockCreated != null)
{
    blockCreated();
}
```

Alternatively, if C# 6 syntax can be used in this project:

```cs
this.BlockCreated?.Invoke();
```

**Comment by doubleyewdee** [comment]
Good catch! I'll take a look at your PR as well. Thanks!

**Comment by doubleyewdee** [comment]
Merged. Going to swap this to C# 6 syntax in a subsequent change. Thanks.
