### ISSUE TITLE
TryGetBuffer should return false when memory is fragmented

### ISSUE THREAD

**Issue by DanilovSoft** [microsoft/Microsoft.IO.RecyclableMemoryStream#193]
I'm assume that the convention of `TryGetBuffer` is if underlying memory can be easily accessed, then you can have it. But in current circumstances, `TryGetBuffer` simply calls `GetBuffer` wich performs relatively heavy defragmentation. So where is no 'Try' in this approach and performance can suffer when you don't know with which MemoryStream you're working with.

My suggestion is to return true only when underlying memory represented as single block.

### System Configuration

- Microsoft.IO.RecyclableMemoryStream version: 2.1.3
- Environment (Operating system, version and so on): Windows 10 x64

**Comment by DanilovSoft** [comment]
I realized that the success of the `TryGetBuffer` method is SHOULD be tied to 'publiclyVisible' parameter

**Comment by grbell-ms** [comment]
Generally, RMS tries to replicate the API of `MemoryStream` as closely as possible. So, if `GetBuffer` won't throw, `TryGetBuffer` will return `true`.

If you want access the underlying memory without added allocation/copying, use `GetReadOnlySequence` and `GetSpan`/`GetMemory`.
