### ISSUE TITLE
Is the Dispose(false) implementation safe?

### ISSUE THREAD

**Issue by Aethon** [Microsoft/Microsoft.IO.RecyclableMemoryStream#2]
Hey implementors, great job on this project!

I had one question while looking at the code: I notice that you are "touching" another managed object (the manager) from the Dispose method on the stream, even when it is invoked from the finalizer. I was under the impression that was verboten, since the manager could have been gc'ed by the time the finalizer runs.

Is that no longer the case, generally?

**Comment by doubleyewdee** [comment]
That's a good point actually. Need to discuss this with Ben and I'll get back to you.

**Comment by benmwatson** [comment]
You are correct, in general. In this particular case, we're showing the bias of the original application of this library. There is an assumption that the stream manager will last the lifetime of the process, thus, except for shutdown, if a stream is finalized, the manager is guaranteed to exist.

If we were to change this to make it generally safe without an assumption of manager's lifetime, it would remove some of the tracking and debugging benefits. The Dispose(false) path does check if if the app is shutting down, but it doesn't encompass all the dangerous code.

**Comment by doubleyewdee** [comment]
This should be fixed as of 1.1 I believe.
