### ISSUE TITLE
Blocks list initial capacity

### ISSUE THREAD

**Issue by lbargaoanu** [microsoft/Microsoft.IO.RecyclableMemoryStream#203]
Another small allocation :)
The initial capacity is [one](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/a2ef5ed3e23161aa1bf98ed0fb840fdc8eb60645/src/RecyclableMemoryStream.cs#L98). Then, in the constructor, the capacity is increased to two ([the default settings](https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/blob/a2ef5ed3e23161aa1bf98ed0fb840fdc8eb60645/src/RecyclableMemoryStream.cs#L1559)). This causes an allocation.
Perhaps leave the default (zero in .Net 5) and avoid the allocation? Or if one is hepful in other cases, start with zero just in the default case?

**Comment by paulomorgado** [comment]
`List<T>` grows doubling the size of the array when it needs to grow.

When the length of the array is `0`, the first growth is to 4.

With an initial length of `1`, the list of blocks will grow to `2` before growing to the initial `4`.

To prevent unneed allocations, the allocation of the `List<byte[]>` could happen on first use only. But that cost is only acceptable if it is expected that instances of the stream are created and "not used".

**Comment by benmwatson** [comment]
We don't let List use its own growth algorithm--it's always in terms of setting a specific capacity, and it always grows, so I think having an empty List to start makes sense. I think most streams would get used, so I wouldn't want to add overhead of checking for a null list everywhere.
