### ISSUE TITLE
With large buffer pool sizes MaximumFreeLargePoolBytes isn't useful for controlling memory usage

### ISSUE THREAD

**Issue by cryolithic** [microsoft/Microsoft.IO.RecyclableMemoryStream#222]
As the Max bytes value is applied to all pools, it can lead to many slack buffers in pools that may have had a burst of usage, and then dropped off. Looking at the distribution of requests in my usage case, my largest buffer would need to be 1GB, with a regular turnover of 4 in use at a given time. With that max value of 4GB, that could lead to a significant amount of memory in buffers that were needed during a rare high point of utilization, but then dropping off to a smaller need.

It may be useful to set either a maximum free bytes for the whole manager, or to decay buffers based on age, or move them to other pools if possible?

Here's a small set of sample data I pulled today.
Linear with 100MB Large Buffer Miultiples
![image](https://user-images.githubusercontent.com/11305845/156434533-91e7b7e2-af89-45f8-8061-bcadc6240db5.png)

Exponential may be worse as there is a requirement for a greater number of larger buffers, however I haven't tested to see if they are better utilized.
![image](https://user-images.githubusercontent.com/11305845/156436243-95f24b76-bfbe-4aa8-b5ef-5d26d4039cb6.png)

Any thoughts on potential solutions? I suspect this may be out of scope for the project, if so let me know and I'll fork it for a potential solution.

**Comment by grbell-ms** [comment]
This sounds similar to what `ArrayPool` does.
https://source.dot.net/#System.Private.CoreLib/TlsOverPerCoreLockedStacksArrayPool.cs,3a27238484a936f9,references

**Comment by benmwatson** [comment]
There have been a handful of trimming requests over the years. I've resisted so far because they were a bit too specific. The other issue is that the whole point of this library is to prevent expensive GCs, and releasing a ton of buffers at once could cause a full GC. 

One thought I've had is to start tracking the most-recently used time for each buffer in the pool, and provide a Trim(TimeSpan) method on the manager. That should be pretty cheap, and could be used only when needed by people who want it.

**Comment by cryolithic** [comment]
The GC hit was my concern as well. I may just need to use multiple managers, separating the smaller ( <256mb or so) with a lower maxFree, and a larger one, allowing me to keep a pool that can hold X items without the smaller ones ballooning up

**Comment by benmwatson** [comment]
If you have very disparate buffer needs, then a second manager could make sense. I will close for now, but if you think an explicit trimming feature would be nice, please re-open.

**Comment by cryolithic** [comment]
I'm going to try and experiment with a max number of buffers vs max bytes. That may solve my issue. I'll post back with results when i have a chance
