### ISSUE TITLE
Buffer size absurdly large

### ISSUE THREAD

**Issue by NVentimiglia** [Microsoft/Microsoft.IO.RecyclableMemoryStream#23]
I was benchmarking this library when I noticed that the buffer length from GetBuffer was very large. E.G., a 2056 length string resulted in a buffer with a length of 131072. Moreover, my serialization of serval floats (length 146) also resulted in a buffer with a length of 131072.

 I really would not like memory chunks of 130kb. That scares me.

I feel like I am missing a very basic implementation detail. Am I possibly doing it wrong or is this a bug ?

**Comment by wengys** [comment]
@NVentimiglia, 131072 is the default block size. You can change blocksize when creating new RecyclableMemoryStreamManager instance. 

You should take a look at the announcement blog post, and get the implementing detail you need.
