### ISSUE TITLE
Add NET6 target

### ISSUE THREAD

**Issue by ovska** [microsoft/Microsoft.IO.RecyclableMemoryStream#239]
Current LTS target .NET 6 should be added.
Conversely, .NET 5 and .NET Core 2.1 are out of support and should probably be dropped.

**Comment by kerams** [comment]
Why? What do we gain?

**Comment by LeaFrock** [comment]
> Current LTS target .NET 6 …… NET 5 and .NET Core 2.1 are out of support

I can understand it's not worth releasing a new version only for a simple change of target frameworks.  But if the next version 
 releases, why not do so in passing? @kerams

**Comment by benmwatson** [comment]
Please see comments on the PR for why we are not going to do this. #240
