### ISSUE TITLE
RecyclableMemoryStream.ToString should not throw if disposed

### ISSUE THREAD

**Issue by gosss** [microsoft/Microsoft.IO.RecyclableMemoryStream#242]
From https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-6.0
Notes to Inheritors
Your [ToString()](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-6.0#system-object-tostring) override should not throw an exception.

This comes up for us in unit tests that use moq. it remembers all invocations and their parameters and, if a verification failure happens, it will ToString all of the parameters to make the error report but in the case of Stream arguments, if it was a RecyclableMemoryStream that has long since been disposed, the exception from its ToString prevents meaningful diagnostics from moq.

**Comment by benmwatson** [comment]
@gosss Please take a look at PR #244

**Comment by gosss** [comment]
Thanks for the fix, sorry i missed the PR
