### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by foromer4** [Microsoft/Microsoft.IO.RecyclableMemoryStream#25]
I am using the RecycableMemoryStream inside a using clause,
when I profile a long runnig process I see it has ~100K instances of RecycableMemoryStream and ~200K instances of byte[] .
Is it possible this is due to a memory leak? I am not using more than a few instances at a time.

**Comment by benmwatson** [comment]
Could it be that there just hasn’t been a GC, so all the previous instances are still in memory?

**Comment by foromer4** [comment]
Not likely, I'm using Ants memory profiler, and each snapshot is said to cause full gc:
see: http://www.red-gate.com/products/dotnet-development/ants-memory-profiler/walkthrough
"
...
When we click the Take Memory Snapshot button, the memory profiler forces a full garbage collection and takes a snapshot of the heap memory it is using.
...
"

**Comment by foromer4** [comment]
Sorry - Looks like a bug in my code.closing this issue
