### ISSUE TITLE
Enable nullable annotations and warnings

### ISSUE THREAD

**Issue by Flash0ver** [microsoft/Microsoft.IO.RecyclableMemoryStream#254]
Apply C# 8.0's _Nullable Reference Types_ by setting `<Nullable>enable</Nullable>` and annotating the entire library with nullable reference types.
As of `v2.2.1`, `LangVersion` is already set to `9.0`.

This change may warrant an increment of the major version number:
Enabling nullable annotations is basically emitting and applying both `System.Runtime.CompilerServices.NullableAttribute` and `System.Runtime.CompilerServices.NullableContextAttribute` which, I believe, should be binary compatible. However, if a consumer has either `<Nullable>warnings</Nullable>` set or is using `#nullable enable warnings` at the consuming code lines while also having `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`, this would be a source breaking change.
Perhaps to consider taking in other _major_ changes, such as #165.

**Comment by Flash0ver** [comment]
I'd be happy to grab this issue.

**Comment by benmwatson** [comment]
I'm seeing that we're starting to get a critical mass of features suitable for a v3.

And PRs always get faster attention than issues. :)

**Comment by Flash0ver** [comment]
I'm afraid I'm uncertain whether I understand correctly:
May I go ahead and submit a PR for that?

**Comment by benmwatson** [comment]
Yes, please go do submit a PR, but I'll probably hold off on approving it until I start some of the other breaking changes, and get us on a new baseline. So no rush.
