### ISSUE TITLE
Change Target Framework from `net5.0` to `net6.0`

### ISSUE THREAD

**Issue by Flash0ver** [microsoft/Microsoft.IO.RecyclableMemoryStream#255]
_.NET 5.0_ is end of support since _May 10, 2022_.
Also, `netcoreapp2.1` has reached end of support and may be dropped.

When also updating the `LangVersion` to `10.0`, the library'd use _Constant Interpolated Strings_ and _Interpolated String Handlers_.

This would imply incrementing the major version number, right? Removing a target framework is a breaking change, isn't it?
Perhaps to consider taking in other _major_ changes, such as #165.

**Comment by Flash0ver** [comment]
I'd be happy to grab this issue.

**Comment by benmwatson** [comment]
Hi @Flash0ver, 

This has been discussed before, in #239. Please read through that and the linked PR. Removing a target would be a breaking change, and would not inherently add to the value of the library.

As you say, this would be a better candidate for a new major version. I'd be open to both moving from net5 to net6, and doing the changes in #165 for a v3.

If there are some features that can be added, without breaking changes, that depend on new frameworks, they can certainly be added without bumping to a new major.

**Comment by Flash0ver** [comment]
Oops, please apologize ... I totally did not search for already closed duplicates of this ... it won't happen again.
I did not consider keeping no longer supported TFMs for libraries so far.
Thank you for your feedback and the clarification.
