### ISSUE TITLE
RecyclableMemoryStream exhausts all available RAM if requestedSize > (int.MaxValue - BlockSize)

### ISSUE THREAD

**Issue by elgonzo** [Microsoft/Microsoft.IO.RecyclableMemoryStream#26]
When a RecyclableMemoryStream is created where _requestedSize_ satisfies the condition:

`(numberOfRequiredBlocks * BlockSize) > int.MaxValue`
where
`numberOfRequiredBlocks = Ceil( requestedSize / blockSize )`

then the method _RecyclableMemoryStream.EnsureCapacity_ loops until all available virtual address space is exhausted (running x64 code with much more than 10GB RAM available; thus it is not a problem with regard to available RAM or 32bit virtual address space).

The problem occurs at the execution of the following [while loop](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/blob/master/src/RecyclableMemoryStream.cs#L843-L846):

```
while (this.Capacity < newCapacity)
{
    blocks.Add((this.memoryManager.GetBlock()));
}
```

When given a _requestedSize_ that satisfied the condition shown at the beginning of my post, the property _Capacity_ will eventually overflow, thus not allowing the while-loop to exit. (1)

Proposed fix: Either make the _Capacity_ property a _long_ type (2), or add a sanity check that prevents _Capacity_ from overflowing...

---

Foot notes:

(1) Strictly speaking, whether the while-loop eventually exits depends -- aside from the virtual memory size -- on the chosen block size and an "appropriate" _requestedSize_ value. With the default block size of 128K, the Capacity property will overflow and eventually reach the value 0 again, thus turning the while-loop effectively into an infinite loop. When choosing some other 'odd' block size, Capacity property will still overflow, but not necessarily reach precisely 0 again, thus possibly allowing the while loop to eventually exit -- but chances are good that all RAM has been exhausted already before that would happen.

(2) It would be nice if RecyclableMemoryStream would support stream sizes larger than 2GB (i.e. not using int types but long types for all concerned method arguments/variables/fields/properties). It is not really a show stopper though, as one can split large data blobs into multiple MemoryStream objects that are wrapped into a custom Stream class representing those multiple MemoryStreams as one continuous stream...

**Comment by doubleyewdee** [comment]
Making Capacity long isn't possible (note it's an override). Writing a repro test currently so I can validate a fix.

**Comment by elgonzo** [comment]
I didn't notice that Capacity is an overridden property from MemoryStream, when i encountered the problem. Makes me wonder why the property _RecyclableMemoryStreamManager.MaximumStreamCapacity_ is a long, though. Shouldn't it be an int as well?

**Comment by elgonzo** [comment]
Unfortunately, there is still an issue when RecyclableMemoryStream with a size close to or exactly of **int.MaxValue** is being requested.

The commit from June 30th attempts [clamping the property _RecyclableMemoryStream.Capacity_](https://github.com/doubleyewdee/Microsoft.IO.RecyclableMemoryStream/blob/master/src/RecyclableMemoryStream.cs#L317-L318) to prevent it from overflowing:
```
long size = this.blocks.Count * this.memoryManager.BlockSize;
return (int)Math.Min(int.MaxValue, size);
```
However, the calculation of the long variable `size` is incorrect. It will multiply two _int_ values, and will only convert the _int_ result to an _long_ value. Thus, the overflow can still happen and the variable `size` becoming negative in the if the block count is becoming sufficiently high.

An example:
When requesting a _RecyclableMemoryStream_ with size of `int.MaxValue`, the block count will eventually reach 16384 (assuming the standard block size of 131072). 

The _int_ multiplication 16384*131072 will result in the `size` variable (and in consequence the `Capacity` property) having a negative value of -2147483648. This will break the _while_ loop in the method _RecyclableMemoryStream.EnsureCapacity_, which again would lead to exhaustion of the available virtual memory.

_____
Suggested fix:

To fix the issue, the multiplication needs to be forced to operate on _longs_. Casting one or both of the multiplicands as a _long_ will do this:
```
long size = (long) this.blocks.Count * this.memoryManager.BlockSize;
return (int)Math.Min(int.MaxValue, size);
```

____
Additionally, [the test method _GiantAllocationSucceeds_](https://github.com/doubleyewdee/Microsoft.IO.RecyclableMemoryStream/blob/master/UnitTests/Tests.cs#L434-L444) is not able to find this issue.
To detect this issue (using the default block size of 128KB), the requested stream size must be at least `int.MaxValue - (mgr.BlockSize + 2)` .

The reason is the following: _int.MaxValue_ equals 0x7fffffff. To satisfy a requested stream size of 0x7fffffff with the default block size of 128KB (=0x20000), 16384 blocks are required. Note that the last block is not fully used, its used capacity is 0x1ffff.

However, the largest stream size requested by the unit test is only  `int.MaxValue - (mgr.BlockSize + 1)`.
`(mgr.BlockSize + 1)` equals 0x1ffff - which means only 16383 blocks are needed.

With only needing 16383 blocks, the unit test fails to test a scenario where the `RecyclableMemoryStream.Capacity` property could overflow (i.e., scenarios where 16384 blocks would be needed).

I would suggest to let the unit test request a stream size of exactly _int.MaxValue_ to make sure that the clamping of the _Capacity_ property works. If it works with a stream size of _int.MaxValue_ then it should also work with any other stream sizes (as they can only be less than _int.MaxValue_).

**Comment by doubleyewdee** [comment]
Pretty sure the PR above resolves this per the comment (thank you for the excellent diagnosis). Will give a few days for someone to review before just merging in case any concerns arise. Thanks!
