### ISSUE TITLE
NullReferenceException possible with M.IO.RecyclableMemoryStream.Dispose(true)

### ISSUE THREAD

**Issue by kevincha99** [microsoft/Microsoft.IO.RecyclableMemoryStream#260]
The finalizer implementation for RecyclableMemoryStream can throw exceptions in some cases.  One case I've seen is that in low-memory, the allocation for this.blocks (which is implicit, and thus happens before the regular constructor) can throw, leaving this.memoryManager null which the finalizer assumes can never happen.  I suggest moving the blocks allocation explicitly into the constructor to guard against this, or place null guards in Dispose to exit if the object isn't properly initialized.

**Comment by benmwatson** [comment]
Good catch, thank you.
