### ISSUE TITLE
Using memory stream with httpClient post

### ISSUE THREAD

**Issue by stefan2410** [microsoft/Microsoft.IO.RecyclableMemoryStream#262]
Hi, 
I upload filestreams using httpClient.   I would prefer to upload directly recyclable memory streams , This can be done  using  a StreamContent class. But at first to     Convert.ToBase64String(stream.ToArray());    This is bad for the  RecyclableStream. 
Is there any other way?

**Comment by sungam3r** [comment]
`Convert.ToBase64String` contains overload with `ReadOnlySpan<byte> bytes` argument. But you still allocates a string. I'd suggest to try `Convert.TryToBase64Chars()` instead to and leverage pooling on top of this as much as possible.

**Comment by stefan2410** [comment]
@sungam3r  thanks for the advice about `Convert.TryToBase64Chars()`, but  I'm forced  to use Standard 2.0 because of external libraries.     I worry more about the stream.ToArray() and the consequences.

**Comment by benmwatson** [comment]
Can you share some sample code of how you're using the StreamContent class with the RMS? I see that StreamContent can be initialized directly with a stream--why not do that? 

Alternatively, you could use RMS.GetBuffer(), but you have to use the Length property to know how much of the stream is valid.

But generally, I recommend using the ReadOnlySpan interface.
