### ISSUE TITLE
Is there a plan to contribute to the dotnet/runtime?

### ISSUE THREAD

**Issue by Varorbc** [microsoft/Microsoft.IO.RecyclableMemoryStream#263]
Is there a plan to contribute to the dotnet/runtime?

**Comment by benmwatson** [comment]
It has been discussed internally before. 

It's fairly niche functionality, so I'm not sure it's a good fit.

**Comment by MichelZ** [comment]
They do have <some> overlapping functionality already with `ArrayPool<T>`,  `MemoryPool<T>` right?

**Comment by benmwatson** [comment]
Yes, there is overlapping functionality. I think that one potential issue is that RecyclableMemoryStream is very opinionated. It has been made more generic over the years, but it really wants you to use it in a particular way. I think that is a justifiable concern for inclusion in the runtime.
