### ISSUE TITLE
Continous benchmarking

### ISSUE THREAD

**Issue by lechu445** [microsoft/Microsoft.IO.RecyclableMemoryStream#277]
As this library is performance oriented, I think benchmark tests could be useful to spot any perf regressions. Also performance results can motivate contributors to improve the results.

As a first step, I'd suggest to use [BenchmarkDotNet](https://benchmarkdotnet.org) for the tests.

And in second step prepare Github action using [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark) to enable Continous Benchmarking.

**Comment by benmwatson** [comment]
Agreed. This would be a great thing. If you want to get this started with some sample benchmarks, I'd love to see a PR.
