### ISSUE TITLE
Upgrade blocker: Recent change of GetStream() to return RecyclableMemoryStream instead of MemoryStream

### ISSUE THREAD

**Issue by satishc2437** [microsoft/Microsoft.IO.RecyclableMemoryStream#330]
Hi,
The below change in v3.0.0 version is blocking Upgrade since it breaks contracts in dependent packages using RecyclableMemoryStream.

"All overloads of RecyclableMemoryStreamManager.GetStream now return type RecyclableMemoryStream instead of MemoryStream."

Please revert this change.

Thanks,
Satish

**Comment by sungam3r** [comment]
See conversation from https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/issues/324.
