### ISSUE TITLE
FileStreamResult: ObjectDisposedException: Cannot access a disposed object. 

### ISSUE THREAD

**Issue by vitali-karmanov** [microsoft/Microsoft.IO.RecyclableMemoryStream#336]
Hello,

What is the right way of using a RecyclableMemoryStreamManager with FileStreamResult? I'm having the following issue:

<img width="815" alt="image" src="https://github.com/microsoft/Microsoft.IO.RecyclableMemoryStream/assets/40288109/6b439dc8-aed1-440f-9940-6c692bafebf7">

```
public class PdfFileAttachment
{
    public byte[] FileBytes { get; set; }
    public string ContentType { get; set; }
}

PdfFileAttachment pdfFileAttachment = await _pdfService.GetPdfFileAttachment();

var options = new RecyclableMemoryStreamManager.Options()
{
    BlockSize = 1024,
    LargeBufferMultiple = 1024 * 1024,
    MaximumBufferSize = 16 * 1024 * 1024,
    GenerateCallStacks = true,
    AggressiveBufferReturn = true,
    MaximumLargePoolFreeBytes = 16 * 1024 * 1024 * 4,
    MaximumSmallPoolFreeBytes = 100 * 1024,
};

var manager = new RecyclableMemoryStreamManager(options);

using (var memoryStream = manager.GetStream())
{
    memoryStream.Write(pdfFileAttachment.FileBytes, 0, pdfFileAttachment.FileBytes.Length);
    
    return new FileStreamResult(memoryStream, pdfFileAttachment.ContentType);
}
```

The end goal is to return a pdf file that is stored in a byte[].

Thank you!

**Comment by sgorozco** [comment]
I think you should remove the using() statement surrounding the
manager.GetStream() call  -  it is automatically disposing the stream
before the calling function has a chance to receive the FileStreamResult
you are returning.

**Comment by vitali-karmanov** [comment]
If I remove the **using** and I added **pdfFileStream.Seek(0, SeekOrigin.Begin)** before the return it works.

```
public class PdfFileAttachment
{
    public byte[] FileBytes { get; set; }
    public string ContentType { get; set; }
}

PdfFileAttachment pdfFileAttachment = await _pdfService.GetPdfFileAttachment();

var options = new RecyclableMemoryStreamManager.Options()
{
    BlockSize = 1024,
    LargeBufferMultiple = 1024 * 1024,
    MaximumBufferSize = 16 * 1024 * 1024,
    GenerateCallStacks = true,
    AggressiveBufferReturn = true,
    MaximumLargePoolFreeBytes = 16 * 1024 * 1024 * 4,
    MaximumSmallPoolFreeBytes = 100 * 1024,
};

var manager = new RecyclableMemoryStreamManager(options);

var memoryStream = manager.GetStream();

memoryStream.Write(pdfFileAttachment.FileBytes, 0, pdfFileAttachment.FileBytes.Length);

pdfFileStream.Seek(0, SeekOrigin.Begin);

return new FileStreamResult(memoryStream, pdfFileAttachment.ContentType);

```

However, doesn't removing the **using** kind of defeat the purpose of the RecyclableMemoryStream by not disposing the stream?

Thank you!

**Comment by sgorozco** [comment]
When you dispose of the stream, the recyclable buffers, which act as storage for the stream, are returned to their pool. It's important to dispose of the stream, but make sure to do this after you've processed the FileStreamResult you're returning. The Dispose() method call, whether explicit or implicit through the using() statement, should be made from outside the method that creates and returns the FileStreamResult.

**Comment by steve-warren** [comment]
`FileStreamResult` is automatically disposed per `FileStreamResultExecutor.ExecuteAsync`:

https://github.com/dotnet/aspnetcore/blob/d9df235c2e6d41b65d8e860c5e209d9df8cbcae1/src/Mvc/Mvc.Core/src/Infrastructure/FileStreamResultExecutor.cs#L31
