### ISSUE TITLE
NetStandard Support?

### ISSUE THREAD

**Issue by mj1856** [Microsoft/Microsoft.IO.RecyclableMemoryStream#39]
It would be helpful if this library was re-targeted to build for [.Net Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library), so we could use it in .net core projects and other places.

Thanks!

**Comment by doubleyewdee** [comment]
We'll look at this soon, but are currently waiting for the unified msbuild 15 experience to allow multi-targeting frameworks including .NET standard (the current build process is... not good).

**Comment by mj1856** [comment]
Any update, now that VS2017 has shipped?

**Comment by doubleyewdee** [comment]
See PR #41 which I'll discuss w/ some folks here and get moving on ASAP.

**Comment by doubleyewdee** [comment]
Fixed with #41

**Comment by Mynguss** [comment]
Please remove me from this list.


Richard Edwards
CEO

[cid:image001.png@01D2AEBF.42DB71B0][cid:image002.png@01D2AEBF.42DB71B0]<http://datashaka.com/non-techie/2013/11/datashaka-wins-strata-london-start-showcase-2013/>[cid:image003.png@01D2AEBF.42DB71B0]<http://datashaka.com/non-techie/2013/11/datashaka-ceo-selected-for-silicon-valley-comes-to-uk-100-club/>[cid:image004.png@01D2AEBF.42DB71B0]<http://s2ds.org/>
+44 (0) 7703 193188

@DataShaka<https://twitter.com/datashaka>
