### ISSUE TITLE
Stream disposed too soon

### ISSUE THREAD

**Issue by MatthewSteeples** [Microsoft/Microsoft.IO.RecyclableMemoryStream#40]
using (var ms = memoryStreamManager.GetStream(nameof(ZipOutputStreamHelper)))
    {
        using (StreamWriter writer = new StreamWriter(ms))
        using (JsonTextWriter jsonWriter = new JsonTextWriter(writer))
        {
            var ser = new JsonSerializer();
            ser.Serialize(jsonWriter, sequence);
            jsonWriter.Flush();
        }
        return ms.ToArray();
    }

We use a pattern like this in our code. Basically, the implementation of the JsonTextWriter is such that it doesn't finish off writing to the stream until it is disposed. Calling Flush doesn't seem to finalise it. This worked fine as a MemoryStream, but not as a RecycledMemoryStream. Because Streams call Dispose on their underlying Streams we end up disposing the RecycledMemoryStream before we access the array.

Is there a way to change this at all? Or is it going to be a case of finding a way to correct the behaviour of the JsonTextWriter so that we can finalise the stream before calling ToArray?

**Comment by Rattenkrieg** [comment]
Probably you should use `StreamWriter` constructor with `leaveOpen` parameter.

**Comment by MatthewSteeples** [comment]
That was exactly it. Thanks
