### ISSUE TITLE
Release nuget package with net standard support

### ISSUE THREAD

**Issue by arpit-nagar** [Microsoft/Microsoft.IO.RecyclableMemoryStream#43]
As netStandard code is already merged in master.
Can you please publish a nuget package which supports net standard?

**Comment by arpit-nagar** [comment]
Any updates on this ??

**Comment by damianh** [comment]
Release the package @doubleyewdee ! :)

**Comment by doubleyewdee** [comment]
Sorry! Had some issues with our code signing infrastructure. Should be out tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doubleyewdee** [comment]
Done. https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/1.2.2

**Comment by arpit-nagar** [comment]
Thanks @doubleyewdee
