### ISSUE TITLE
RecyclableMemoryStream class should override TryGetBuffer

### ISSUE THREAD

**Issue by BrannonKing** [microsoft/Microsoft.IO.RecyclableMemoryStream#45]
Please override `TryGetBuffer` (to call `GetBuffer()` internally) to create the appropriate `ArraySegment` object.

**Comment by nathanaeljones** [comment]
This is a blocker - it breaks the MemoryStream interface contract.

**Comment by benmwatson** [comment]
TryGetBuffer was introduced in .NET 4.6. A new target will have to be added.
