### ISSUE TITLE
Add ReadFully() method

### ISSUE THREAD

**Issue by coderb** [microsoft/Microsoft.IO.RecyclableMemoryStream#47]
Can you add a `ReadFully(Stream stream)` method to `RecyclableMemoryStream`?

This could save an intermediate buffer allocation and a lot of memory copying.

I took a stab at it with the caveat that the `RecyclableMemoryStream` can't be using a large buffer.  You may want to remove this constraint.

You'll also probably want to have `RecyclableMemoryStreamManager.GetStream()` return `RecyclableMemoryStream` so that the method is accessible without a cast.

```
        public void ReadFully(Stream stream) {
            if (this.largeBuffer != null) {
                throw new InvalidOperationException();
            }

            while (true) {
                EnsureCapacity(this.length + 1);
                var blockAndOffset = GetBlockAndRelativeOffset(this.position);
                var block = this.blocks[blockAndOffset.Block];

                int count = stream.Read(block, blockAndOffset.Offset, block.Length - blockAndOffset.Offset);
                if (count == 0) {
                    break;
                }
                long end = (long)this.position + count;
                this.position = (int)end;
                this.length = Math.Max(this.position, this.length);
            }
        }

```

**Comment by doubleyewdee** [comment]
Where are you seeing intermediate allocations? At first blush this doesn't make sense to me as an addition to this library, and it might be more valuable to look at the performance of whatever Stream derivative's CopyTo implementation you're using instead...

**Comment by coderb** [comment]
I'm reading from a `NetworkStream` which does a byte[] allocation inside `CopyTo`.

This would also introduce a extra copying, first to the read buffer then to the memory stream.

Please reconsider adding ReadFully().  It is appropriate for high performance code.

**Comment by benmwatson** [comment]
Closing this. Please submit PR if feel this is a good fit for this library, and we will re-review.
