### ISSUE TITLE
Performance opportinities

### ISSUE THREAD

**Issue by buybackoff** [microsoft/Microsoft.IO.RecyclableMemoryStream#48]
I have just played with a profiler and massively increased the performance of my RMS fork for my primary use case of write/read small buffers of several Kbs.  https://github.com/Spreads/Spreads/commit/cbeac8f6a295b007b1110dc31d1100f0a69cc08a

* Aggressively inlining all methods that are used internally. E.g. Capacity.
* Making all methods related to event tracing conditional to a compiler symbol to avoid needless method calls.
* Using System.Buffers array pool (modified to optionally return exact buffer sizes when requested) instead of ConcurrentBag.
* Using [vectorized memory copy](https://github.com/Spreads/Spreads/commit/a18b6360877c8583a75402584bd15269210ae09d) instead of `Buffer.BlockCopy`.
* Pooling of RMS instances using Roslyn's ObjectPool implementation.
* Manual implementation of `WriteByte` instead of redirecting to `Write` via a temporary `byte[1]`. I also added non-virtual SafeWriteByte.
* Using ThrowHelper for better inlining and less code size.

Some of this is directly applicable to the original implementation. My fork is now incompatible with upstream so I cannot create a PR, just put it there FYI & discussion.

I had the idea of integrating RMS with System.Buffers shared pool for a long time - not only this is faster, but also reduces memory by avoiding a separate pool. But the default shared pool implementation could return a buffer larger that the requested size, so I created a custom implementation with a parameter `exactSize`. Without shared pool modifications RMS could work with ArraySegments internally - that shouldn't be slower. And given that the shared pool returns a buffer that could be larger only by a power of two, that larger buffer could be split into several blocks and RMS will just increase capacity by more than one block. In `Dispose()` we just need to check if currently returning ArraySegment has the same buffer as previous and do not return it twice.

**Comment by clarkis117** [comment]
@buybackoff  There's also an atomic dispose check being called before most methods. I'm not exactly sure that if that check needs to be atomic.

This:
```
       private bool Disposed => Interlocked.Read(ref this.disposedState) != 0;

        private void CheckDisposed()
        {

            if (this.Disposed)
            {

                throw new ObjectDisposedException($"The stream with Id {this.id} and Tag {this.tag} is disposed.");
            }
        }
```

**Comment by buybackoff** [comment]
Interlocked.Read is [not needed](https://msdn.microsoft.com/en-us/library/system.threading.interlocked.read%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) on x64 and hopefully implemented well and adds no overhead (and very little on other platforms). My version is before RMS was made thread-safe so I didn't profile the effect. But if `CheckDisposed()` is not inlined - which is likely due to `throw` inside and lack of `AggressiveInlining` - then the non-inlined method call is likely more expensive vs Interlocked.Read. Especially given that the `if` false branch is almost always taken.

**Comment by clarkis117** [comment]
@buybackoff  I did a few benchmarks using a manual implementation of the WriteByte Method. The benchmarks measure the amount of time it takes to write 1MB, using the WriteByte method.

Manual Implementation of WriteByte without changing any external function calls.

  Method | Job | Platform |     Mean |     Error |    StdDev |
------------- |---- |--------- |---------:|----------:|----------:|
 WriteByteNew | x64 |      X64 | 26.86 ms | 0.0438 ms | 0.0410 ms |
 WriteByteOld | x64 |      X64 | 60.38 ms | 0.2771 ms | 0.2592 ms |
 WriteByteNew | x86 |      X86 | 36.11 ms | 0.1226 ms | 0.1087 ms |
 WriteByteOld | x86 |      X86 | 81.80 ms | 0.0296 ms | 0.0247 ms |

Changing Interlocked.Read(ref long) in Dispose getter, to just reading the disposeState field (no Interlocked.Read)

  Method | Job | Platform |     Mean |     Error |    StdDev |
------------- |---- |--------- |---------:|----------:|----------:|
 WriteByteNew | x64 |      X64 | 21.81 ms | 0.1058 ms | 0.0989 ms |
 WriteByteOld | x64 |      X64 | 51.80 ms | 0.3159 ms | 0.2800 ms |
 WriteByteNew | x86 |      X86 | 23.19 ms | 0.0170 ms | 0.0159 ms |
 WriteByteOld | x86 |      X86 | 63.66 ms | 0.2278 ms | 0.1778 ms |

Manually Inlining Dispose check and getter property, still using Interlocked read

       
Method | Job | Platform |     Mean |     Error |    StdDev |
------------- |---- |--------- |---------:|----------:|----------:|
 WriteByteNew | x64 |      X64 | 25.08 ms | 0.0051 ms | 0.0045 ms |
 WriteByteOld | x64 |      X64 | 59.23 ms | 0.2250 ms | 0.2104 ms |
 WriteByteNew | x86 |      X86 | 33.73 ms | 0.0090 ms | 0.0084 ms |
 WriteByteOld | x86 |      X86 | 81.53 ms | 0.0245 ms | 0.0205 ms |

**Comment by benmwatson** [comment]
Feel free to submit a PR for some of these issue. We're always interested in better performance.

**Comment by buybackoff** [comment]
It wasn't an issue per se but reporting results of applying profiler & some tweaks. I wonder what are your current use cases for memory streams, but with Span/Memory/Pipelines I do not see how to use that for new code.
