### ISSUE TITLE
Nuget package contains debugging symbols without source

### ISSUE THREAD

**Issue by Crossbow78** [microsoft/Microsoft.IO.RecyclableMemoryStream#49]
In the [Publish Symbols] step during a build on our build server, the following error occurs:

> ##[error]Indexed source information could not be retrieved from 'F:\tfsagent\_work\13\s\src\[project]\bin\Microsoft.IO.RecyclableMemoryStream.pdb'. Symbol indexes could not be retrieved.

This seems to be caused by the presence of a .pdb file in the Nuget package and the absence of the corresponding source files.

**Comment by doubleyewdee** [comment]
That's correct. Our choices are, I suppose, to simply stop shipping the PDB or figure out how to get public source indexing available. I'll see what options are available for the next release.

The error itself should not be harmful however.

**Comment by Crossbow78** [comment]
It's mostly harmful in the sense that it aborts and fails the "Publish Symbols" build step.

I think it's not a common practice to include a .pdb in the nuget package anyway, so excluding it would be great.

**Comment by hangy** [comment]
The best option would probably be to remove the .pdb from the normal NuGet package and publishing a real symbol package to SymbolSource.org instead.

**Comment by doubleyewdee** [comment]
Yep, fair points. I’ll fix our build automation to resolve this when the next publish occurs.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by phatcher** [comment]
You can include the pdb and use pdblink to link it directly to the GitHub source

**Comment by shorbachuk** [comment]
Any update on this? I am having this issue as well with our build failing because of this...

**Comment by tswanson27** [comment]
+1, we had to revert to an old version to get a project working in TFS

**Comment by markwemekamp** [comment]
+1, are there any other options besides downgrading? I've just updated other packages depending on v1.2.2

**Comment by benmwatson** [comment]
In v1.3.0, PDBs have been removed and are published via a .snupkg instead.
