### ISSUE TITLE
Use in HttpClient

### ISSUE THREAD

**Issue by phatcher** [Microsoft/Microsoft.IO.RecyclableMemoryStream#50]
Is there anyway of making HttpClient use this?

I'm processing files from blob storage of up to 100Mb in a webjob and I'm trying to minimise the amount of disk I/O and also memory churn.

Any other suggestions gratefully received.

**Comment by doubleyewdee** [comment]
Going to close this (not really on-topic / an issue) but basically: yes. If you use the Content property of HttpResponseMessage (e.g. from a GetAsync) you can use something like CopyToAsync in order to copy the response content to any Stream object (incl RMS).
