### ISSUE TITLE
GetBuffer() throws System.UnauthorizedAccessException on .NET Core

### ISSUE THREAD

**Issue by chhuebner** [microsoft/Microsoft.IO.RecyclableMemoryStream#55]
When calling `GetBuffer()` in a .Net Core app, an `UnauthorizedAccessException` ("MemoryStream's internal buffer cannot be accessed.") is thrown.

The reason is that `GetBuffer()` is not marked as **override** when compiled for netstandard. Therefore, the original implementation of `MemoryStream.GetBuffer()` will be called, unless the call is explicitly made on a variable of type `RecyclableMemoryStream`.

```csharp
#if NETSTANDARD1_4
   public byte[] GetBuffer()
#else
   public override byte[] GetBuffer()
#endif
```
I don't know what was the motivation for this conditional compilation, since `MemoryStream.GetBuffer()` has always been virtual.

**Comment by doubleyewdee** [comment]
Actually the motivation came directly from errors related to overriding a non-virtual method. The conditional may need to be updated for newer versions of .NET Core however.. can you share more about your runtime?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by chhuebner** [comment]
Runtime is .Net Core 2.0. 

I now realize that prior to NetStandard 2.0 the class `MemoryStream` had no method `GetBuffer` at all.

**Comment by doubleyewdee** [comment]
Thanks. When this code was implemented netstandard 2.0 wasn’t yet released (so couldn’t be directly targeted). It sounds like I need to add a new target for 2.0 covering changes in that variant.

It’s like 3am here so I might pick this up tomorrow or over the weekend (although PRs are always welcome).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clarkis117** [comment]
@doubleyewdee Here's a good reference on which platforms' implement GetBuffer() : https://apisof.net/catalog/System.IO.MemoryStream.GetBuffer()

**Comment by karldodd** [comment]
Hmmm.. Does this library work on .Net Core 2.0 now?

**Comment by peters** [comment]
@doubleyewdee Do you know when you might be able to land a patch for this issue?

**Comment by qqbuby** [comment]
Any updates?

**Comment by bp74** [comment]
Just had the same problem and couldn't believe that it actually doesn't work. Please provide an updated version of the library.

**Comment by benmwatson** [comment]
I believe this has been resolved now. There are targets for 2.0 as of a month ago. Closing.
