### ISSUE TITLE
RecyclableMemoryStream class should override CopyToAsync

### ISSUE THREAD

**Issue by joshdean2000** [microsoft/Microsoft.IO.RecyclableMemoryStream#57]
Because RecyclableMemoryStream is not overriding the CopyToAsync it means it's using the default one in Stream class which generates a byte[] buffer each time it's called.

This kind of defeats the purpose of using RecyclableMemoryStream.

Not sure why Stream doesn't support overriding CopyTo as well as this would also benefit from being overridden.

**Comment by benmwatson** [comment]
The default implementation of Stream.CopyToAsync now uses ArrayPool and Memory for its temporary buffers. I don't think there is a strong reason to override this behavior at the moment.

**Comment by brunom** [comment]
Overriding CopyTo* would avoid an unnecessary memcpy.

**Comment by benmwatson** [comment]
Fair point. I'll try to look at this issue soon.

**Comment by benmwatson** [comment]
@brunom @joshdean2000 Would you like to review the referenced PR for this issue?

**Comment by paulomorgado** [comment]
Using `Task.Run` is async over sync and that's a bad practice. See [Should I expose asynchronous wrappers for synchronous methods?](https://devblogs.microsoft.com/pfxteam/should-i-expose-asynchronous-wrappers-for-synchronous-methods/).

The thread pool might be a critical component of the system using the stream.

But avoiding allocation is always good. And, if nothing else in the system is using `ArrayPool` there's no reason for `RecyclableMemoryStream` to use it just for this.
