### ISSUE TITLE
Trying to read a huge file 

### ISSUE THREAD

**Issue by Pheros** [microsoft/Microsoft.IO.RecyclableMemoryStream#58]
Hi all, 

I am trying to read a huge file (2.5 gigabyte) file, but it allways ends up with: "Unhandled Exception: System.IO.IOException: Maximum capacity exceeded" and the Ram is allways around 100% taken.  What I am doing wrong?

               `int blockSize = 10;
                int largeBufferMultiple = 1024 * 1024;
                int maxBufferSize = 16 * largeBufferMultiple;

                var manager = new RecyclableMemoryStreamManager(blockSize,
                                                                largeBufferMultiple,
                                                                maxBufferSize);

                manager.GenerateCallStacks = true;
                manager.AggressiveBufferReturn = true;
                manager.MaximumFreeLargePoolBytes = maxBufferSize * 4;
                manager.MaximumFreeSmallPoolBytes = 100 * blockSize;
                RecyclableMemoryStream memoryStream = new RecyclableMemoryStream(manager);
                using (FileStream fileStream = File.OpenRead(@"C:\Temp\test.bin"))
                {
                    

                    // MemoryStream memoryStream = new MemoryStream();
                    fileStream.CopyTo((memoryStream);`

**Comment by shatl** [comment]
> What  I am doing wrong?
You are reading huge file into memory.

First of all it's not a case for this library
Secondly, why do you need whole file in memory? Either read in in chunks or use memory-mapped file api.
