### ISSUE TITLE
[Question] Project status?

### ISSUE THREAD

**Issue by shatl** [microsoft/Microsoft.IO.RecyclableMemoryStream#62]
Hello guys,
is this project still maintained?

**Comment by shatl** [comment]
Since there are no response from the owners, I'm going to create an unofficial build to apply community PRs 
@doubleyewdee @benmwatson any objections?

**Comment by doubleyewdee** [comment]
No objection. I'm very sorry for the lack of responses (100% on me). We made a bunch of changes internally to how we build/deploy Microsoft-owned nuget packages which I've failed to keep up with (and thus failed to take any changes here). I'm traveling for work and busting a couple tight deadlines but I've set aside time to pick this back up.

I'm not sure @benmwatson is getting notifications here so I'll try and poke him as well.

**Comment by buybackoff** [comment]
@shatl FYI, if you haven't seen #48 and my actively maintained [fork](https://github.com/Spreads/Spreads/commits/master/src/Spreads.Core/Buffers/RecyclableMemoryStream.cs) with several improvements, such as integration with the shared array pool for small chunks, RMS object pooling, ref counting, some methods to access internals. Recent version in on NuGet and open to any performance improving ideas.

However, the days of Streams are counted and [Pipelines](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/) + [ReadOnlySequence](https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs) are the future. Just so many code depends on streams and RMS is quite good but temporary solution in the long-run.

**Comment by shatl** [comment]
Thanks @buybackoff I've seen #48 
I'm going to apply PR and address issues in their original order. 

Spreads.Core looks great, but I'm looking for some lightweight library

**Comment by buybackoff** [comment]
@shatl There are a lot of stuff in Spreads.Core for binary and Json serialization that very often rely on RMS and it's internal implementation. E.g. fork of the fastest Utf8Json Json serializer [tries to check](https://github.com/Spreads/Utf8Json/blob/62d0bdf94ff20b0b26e1858516c4da1d8024e6cb/src/Utf8Json/JsonSerializer.cs#L294) the case when RMS is made of a single chunk to avoid copying (no changes to upstream, only `#ifdef`ed integration with RMS and other buffering). And so on. E.g. `BinarySerializer.SizeOf` returns RMS for the cases when it's not possible to calculate exact serialized size without performing actual serialization, for Json case RMS is only Json in Utf8 encoding without any headers.

**Comment by benmwatson** [comment]
We are going to try to get the official builds up and running again and apply some of the PRs. It should take a couple of weeks to get up and going again.

**Comment by benmwatson** [comment]
I'm actively reviewing PRs again, so feel free to submit any of general use to everybody.

**Comment by ovebastiansen** [comment]
When will the official builds start happening? The nuget package hasnt been updated for a while

**Comment by benmwatson** [comment]
I know. I just haven't had the time to setup a new process of getting the package and bits signed, which is a requirement for us to release binaries. I'm really hoping to get it done soon.

**Comment by benmwatson** [comment]
New code is in, new NuGet is published!
