### ISSUE TITLE
Use BufferManager for byte array creation

### ISSUE THREAD

**Issue by imanushin** [microsoft/Microsoft.IO.RecyclableMemoryStream#65]
Summary: for better memory re-usage I suggest using [BufferManager](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.buffermanager) type (which is available from .Net 3.0).

New byte arrays are created here: https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream/blob/master/src/RecyclableMemoryStreamManager.cs#L289

Pros:
* BufferManager is system type, so it can be tuned per each .Net framework implementation.

Cons:
* Looks like this class is not thread safe (please see [SO investigation](https://stackoverflow.com/questions/5697154/is-system-servicemodel-channels-buffermanager-thread-safe)).

**Comment by buybackoff** [comment]
BufferManager is not the best option, even it's namespace suggests it is intended for particular purpose.

There is [shared memory pool](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs) optimized for thread local and detecting memory pressure, but it could return size larger than requested, that breaks RMS in the current design and requires [a check for length](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Buffers/RecyclableMemoryStreamManager.cs#L255-L261). If the goal is to reduce overall app memory usage and share pools then using the shared pool with the check should be OK, or RMS should be redesigned to use `ArraySegments`/`Memory` etc.

There is also a [ConfigurableArrayPool](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Buffers/ConfigurableArrayPool.cs#L84) but the relevant variable to get exact size `MaxBucketsToTry` is [not configurable](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Buffers/ConfigurableArrayPool.cs#L84). It should be set to zero and `!=` condition in the [while loop](https://github.com/dotnet/corert/blob/469ebc56902d485bb35c32b5c9f055c1fce61c62/src/System.Private.CoreLib/shared/System/Buffers/ConfigurableArrayPool.cs#L99) replaced with `<=`.

RMS could just extract [bucket implementation](https://github.com/dotnet/corert/blob/469ebc56902d485bb35c32b5c9f055c1fce61c62/src/System.Private.CoreLib/shared/System/Buffers/ConfigurableArrayPool.cs#L163) from `ConfigurableArrayPool`, it is c.3X faster than `ConcurrentStack` that is used now. Replacing `SpinLock` with [hand-crafted](https://github.com/Spreads/Spreads/blob/9cf9584e95d5b1c60ea040de0a953a5089714ae2/src/Spreads.Core/Buffers/RetainableMemoryPool.cs#L377-L381) lock makes it even faster and is appropriate for this case where the work being done inside the lock is literally a couple of instructions.

**Comment by imanushin** [comment]
@buybackoff , thank you for detailed investigation.

> RMS should be redesigned to use ArraySegments/Memory etc.

I think this is the best option, because we will re-use common solution (which is optimized for now and will be optimized in future).

And I fully agree with "BufferManager is not the best option" according to your arguments
