### ISSUE TITLE
add implementation with int64 capacity

### ISSUE THREAD

**Issue by IvanKonov** [microsoft/Microsoft.IO.RecyclableMemoryStream#72]
add implementation with int64 capacity

**Comment by benmwatson** [comment]
Are there any streams in .Net right now that have greater than 4 GB capacity abilities?

**Comment by benmwatson** [comment]
given that we are a replacement for MemoryStream, which supports only 32-bit streams, I am considering this out-of-scope for now. It's a good idea, in general, though, so I want to consider how it could be integrated in the future.

**Comment by IvanKonov** [comment]
> В сети .Net есть емкость более 4 ГБ?

Yes, for example FileStream

**Comment by IvanKonov** [comment]
A memoryStream with an int64 capacity could be used on servers to convert (e.g. compress) files in memory. For example, when receiving uncompressed files over the network, without intermediate recording them to disk.
