### ISSUE TITLE
Assembly on NuGet in Debug release?

### ISSUE THREAD

**Issue by nycdotnet** [microsoft/Microsoft.IO.RecyclableMemoryStream#78]
I'm testing something with Benchmark.NET and when I attempt to benchmark some code referencing this library, I get the message that Microsoft.IO.RecyclableMemory is non-optimized.  Is it possible that the public NuGet package is accidentally including the debug config?

![image](https://user-images.githubusercontent.com/3755379/69746881-418c8380-1113-11ea-8cab-88cd47090305.png)

**Comment by benmwatson** [comment]
Hmm...that would be a bad mistake. Let me take a look at the binaries and our build and see if something needs fixed here.

**Comment by nycdotnet** [comment]
For what it's worth, the below code uses the exact extension methods that Benchmark.NET is using to test this.  I built the source myself from this repo in both Debug and Release configuration.  Referencing the different assemblies with the below code returned `false` for the Release config and `true` for the Debug config, so I'm fairly confident the public NuGet does have the Debug release by accident.

By the way I loved your book :-)

```csharp

    class Program
    {
        static void Main(string[] args)
        {
            var assembly = Assembly.Load("Microsoft.IO.RecyclableMemoryStream");
            Console.WriteLine($"Are Jit optimizations DISABLED on this assembly? {assembly.IsJitOptimizationDisabled()}");
        }
    }

    internal static class AssemblyExtensions
    {
        internal static bool? IsJitOptimizationDisabled(this Assembly assembly)
            => GetDebuggableAttribute(assembly).IsJitOptimizerDisabled();

        internal static bool? IsDebug(this Assembly assembly)
            => GetDebuggableAttribute(assembly).IsJitTrackingEnabled();

        internal static bool IsTrue(this bool? valueOrNothing) => valueOrNothing.HasValue && valueOrNothing.Value;

        private static DebuggableAttribute GetDebuggableAttribute(Assembly assembly)
            => assembly?.GetCustomAttributes()
                .OfType<DebuggableAttribute>()
                .SingleOrDefault();

        private static bool? IsJitOptimizerDisabled(this DebuggableAttribute attribute) => attribute?.IsJITOptimizerDisabled;

        private static bool? IsJitTrackingEnabled(this DebuggableAttribute attribute) => attribute?.IsJITTrackingEnabled;
    }

```

**Comment by benmwatson** [comment]
Found the problem. The build pipeline was missing the `--no-build` parameter on the pack command, so it was rebuilding and then packing the default version, Debug. I've upload version 1.3.1 to [nuget.org](https://www.nuget.org/packages/Microsoft.IO.RecyclableMemoryStream/1.3.1).

I'll also open a work item for myself to add a build step to verify Release mode of the final binaries.

**Comment by benmwatson** [comment]
1.3.2 should contain the fix

**Comment by nycdotnet** [comment]
Amazing- thanks!!

**Comment by nycdotnet** [comment]
Thanks @benmwatson - my benchmark went from 5.325 us to 4.217 us with less error!!
