### ISSUE TITLE
Add a setting to disallow ToArray

### ISSUE THREAD

**Issue by benmwatson** [microsoft/Microsoft.IO.RecyclableMemoryStream#81]
Calling `ToArray` on a RecyclableMemoryStream should be considered a bug because it wipes out all the benefits of using the library. While the method does work as intended, we could add a setting on RecyclableMemoryStreamManager to cause an exception to be thrown when called.

**Comment by deviousasti** [comment]
An `Obsolete` attribute on the `ToArray()` method might be better?
It's easier to find which code calls `ToArray` at compile time, than at run-time.

**Comment by benmwatson** [comment]
I think `Obsolete` is part of the solution. 

Additionally, thought there is polymorphism. The RMS object might be referenced through a `MemoryStream` base class. If a user wants to really catch and prevent all calls to `ToArray`, it would have to be done at runtime.

**Comment by deviousasti** [comment]
Fair point.

**Comment by deviousasti** [comment]
It's even harder to figure out on Mono where there's no implementation for ETW. A runtime error is a necessity.

**Comment by benmwatson** [comment]
@deviousasti, sorry I didn't even see your PR before I created my own. I believe mine is more complete and includes tests, but please look it over to see if something is missing.

**Comment by deviousasti** [comment]
All good.
