### ISSUE TITLE
Additional Memory<byte> support

### ISSUE THREAD

**Issue by cocowalla** [microsoft/Microsoft.IO.RecyclableMemoryStream#84]
#68 added some support for `RecyclableMemoryStream` to read and write `Span<byte>`/`Memory<byte>`. It would be good to also add support for creating a `RecyclableMemoryStream` from an existing `Memory<byte>`.

`RecyclableMemoryStream.GetStream` already has an overload that takes an existing `byte[]` buffer:

```c#
MemoryStream GetStream(string tag, byte[] buffer, int offset, int count)
```

So the suggestion here is to add a new overload that takes an existing `Memory<byte>` buffer:

```c#
MemoryStream GetStream(string tag, Memory<byte> buffer)
```

**Comment by benmwatson** [comment]
Sounds reasonable. I will try to get to it soon-ish. I'm doing a huge .NET Core migration this week and next, but after that I can relax.
