### ISSUE TITLE
Copying part of a RecyclableMemoryStream to another Stream

### ISSUE THREAD

**Issue by arnaldomontagner** [microsoft/Microsoft.IO.RecyclableMemoryStream#92]
Hello,

The WriteTo method allows me to copy an entire RecyclableMemoryStream to another Stream without any buffer allocation. However, if I need to copy only part of a RecyclableMemoryStream to another Stream, I have to use a buffer.

What is your opinion about creating an overload of WriteTo that takes an offset and length?

**Comment by benmwatson** [comment]
This seems reasonable. Feel free to submit a PR, or I will look at it next week.

**Comment by benmwatson** [comment]
By "next week" I meant when I get the time...it's been tough.

**Comment by arnaldomontagner** [comment]
No worries at all! I've been meaning to make this change myself, but I
haven't found the time yet.
