### ISSUE TITLE
Why does Close call Dispose?

### ISSUE THREAD

**Issue by matanpa** [microsoft/Microsoft.IO.RecyclableMemoryStream#97]
A closed MemoryStream still has uses such as GetBuffer which are now throwing NullReferenceException when migrating to RecyclableMemoryStream. Is it possible not to dispose on close?

**Comment by benmwatson** [comment]
MemoryStream's `Close` method also calls `Dispose`, and `RecyclableMemoryStream` tries to match its API wherever possible. 

I suspect most people are used to `Close` and `Dispose` having the exact same semantics for streams, thus I don't think it's wise to use even `MemoryStream`'s `GetBuffer` after a `Close` call. It's only an accident of implementation that you can still call `GetBuffer` without an exception.

However, with RMS, the semantics are different. Buffers are a shared resource and we have to be stricter about access to avoid hard-to-debug mistakes in usage.
